Repository decentraland/unity-explorer, pull requests merged in 2024-07, with the labels that each got.

#1350 feat: feature flag hostname program arg
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsProviderExtensions.cs
Labels: no QA needed

#1366 feat: support command line '-realm' argument
  Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs
Labels: no QA needed, feature, sdk

#1420 fix: missing map pin reference on EntryPoint GO in Main.unity
  Explorer/Assets/Scenes/Main.unity
Labels: bug, no QA needed, 0-critical

#1414 Enhance emote system + debugging tools
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/CharacterEmoteSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/EmotePlayer.cs
  Explorer/Assets/DCL/WebRequests/Analytics/WebRequestsContainer.cs
  Explorer/Assets/DCL/WebRequests/ArtificialDelayOptions.cs
  Explorer/Assets/DCL/WebRequests/ArtificialDelayOptions.cs.meta
  Explorer/Assets/DCL/WebRequests/Web Artificial Delay.asset
  Explorer/Assets/DCL/WebRequests/Web Artificial Delay.asset.meta
  Explorer/Assets/Scripts/Utility/Storage/PersistentSetting.cs
Labels: enhancement

#1417 Fix: piano delays
  Explorer/Assets/DCL/SDKComponents/AudioSources/AudioSourceExtensions.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/AudioUtils.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Components/AudioSourceComponent.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/csc.rsp
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/csc.rsp.meta
Labels: bug

#1419 fix: attempt to avoid new SHA for each build to ensure caching works.
  Explorer/Assets/Editor/CloudBuild.cs
  scripts/cloudbuild/build.py
Labels: do not merge

#1428 tool: print scene data from goerli by coords
  Explorer/Assets/DCL/Editor/GoerliGetSceneData.cs
  Explorer/Assets/DCL/Editor/GoerliGetSceneData.cs.meta
Labels: no QA needed

#1468 Fix: fixed nullreference of map pin poolable behaviour
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs
Labels: no QA needed

#1503 Fix: fixed minor issue with map pins pooling
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerController.cs
  scripts/package.json
Labels: no QA needed

#1392 feat: local scene development
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/Protocol/DecentralandProtocol/AvatarAttach.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/LocalDevelopment.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/LocalDevelopment.gen.cs.meta
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment.meta
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopment.asmref
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopment.asmref.meta
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopmentController.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopmentController.cs.meta
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldParams.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs
  Explorer/ProjectSettings/ProjectSettings.asset
  scripts/package-lock.json
Labels: no QA needed, feature, sdk

#1449 Feat: added reward panel
  Explorer/Assets/AddressableAssetsData/AssetGroups/Essentials.asset
  Explorer/Assets/DCL/EmotesWheel/EmotesWheelView.cs
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelView.cs
  Explorer/Assets/DCL/ExplorePanel/SystemMenuView.cs
  Explorer/Assets/DCL/Notifications/NewNotification/NewNotificationController.cs
  Explorer/Assets/DCL/Notifications/NotificationTypes/IncomingRewardNotification.cs
  Explorer/Assets/DCL/Notifications/NotificationTypes/IncomingRewardNotification.cs.meta
  Explorer/Assets/DCL/Notifications/NotificationTypes/NotificationType.cs
  Explorer/Assets/DCL/Notifications/NotificationsBus/INotificationsBusController.cs
  Explorer/Assets/DCL/Notifications/NotificationsBus/NotificationsBusController.cs
  Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs
  Explorer/Assets/DCL/Notifications/Serialization/NotificationJsonDtoConverter.cs
  Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
  Explorer/Assets/DCL/PluginSystem/Global/RewardPanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/RewardPanelPlugin.cs.meta
  Explorer/Assets/DCL/Rendering/Menus.meta
  Explorer/Assets/DCL/RewardPanel.meta
  Explorer/Assets/DCL/RewardPanel/Assets.meta
  Explorer/Assets/DCL/RewardPanel/Assets/RewardPanel.prefab
  Explorer/Assets/DCL/RewardPanel/Assets/RewardPanel.prefab.meta
  Explorer/Assets/DCL/RewardPanel/RewardPanel.asmdef
  Explorer/Assets/DCL/RewardPanel/RewardPanel.asmdef.meta
  Explorer/Assets/DCL/RewardPanel/RewardPanelController.cs
  Explorer/Assets/DCL/RewardPanel/RewardPanelController.cs.meta
  Explorer/Assets/DCL/RewardPanel/RewardPanelView.cs
  Explorer/Assets/DCL/RewardPanel/RewardPanelView.cs.meta
  Explorer/Assets/DCL/UI/Popups/PopupCloser.prefab
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/MVC/PopupViewBase.cs
  Explorer/Assets/Scripts/MVC/ViewBase.cs
  Explorer/Assets/Textures/RewardPanel.meta
  Explorer/Assets/Textures/RewardPanel/EllipseParticle.png
  Explorer/Assets/Textures/RewardPanel/EllipseParticle.png.meta
  Explorer/Assets/Textures/RewardPanel/Rays.png
  Explorer/Assets/Textures/RewardPanel/Rays.png.meta
Labels: no QA needed

#1511 chore: enable worlds access through deep links realm param
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsProviderExtensions.cs
  Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInitializationFlowController.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldParams.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs
Labels: no QA needed, feature, sdk

#1545 Fix: adapted reward in progress notification data structure
  Explorer/Assets/DCL/Notifications/NotificationTypes/NotificationType.cs
  Explorer/Assets/DCL/Notifications/NotificationTypes/RewardInProgressNotification.cs
  Explorer/Assets/DCL/Notifications/NotificationTypes/RewardInProgressNotification.cs.meta
  Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs
  Explorer/Assets/DCL/Notifications/Serialization/NotificationJsonDtoConverter.cs
  Explorer/Assets/DCL/PluginSystem/Global/RewardPanelPlugin.cs
Labels: no QA needed

#1588 chore: disable Landscape for local scene development
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
Labels: bug, no QA needed, sdk
