Repository decentraland/unity-explorer, pull requests merged in 2024-01, with the labels that each got.

#239 Jobify scenes sorting
  Explorer/Assets/Scripts/ECS/Prioritization/DistanceBasedComparer.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/IncreasingRadius/ResolveSceneStateByIncreasingRadiusSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/ResolveSceneStateByIncreasingRadiusSystemShould.cs
  Explorer/Assets/Scripts/Utility/ParcelMathJobifiedHelper.cs
Labels: no QA needed

#250 chore: update git ignore with ds_store os-generated file
  .gitignore
Labels: no QA needed, no review

#246 TextShapePlugin register ReleasePoolableComponentSystem
  Explorer/Assets/DCL/PluginSystem/World/TextShapePlugin.cs
Labels: no QA needed

#252 FrameTimeCapBudget to ulong
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/FrameTimeCapBudget.cs
Labels: no QA needed

#257 Hotfix: Get rid of nullability of AudioClip promise as it was not communicated back to ECS
  Explorer/Assets/DCL/SDKComponents/AudioSources/Components/AudioSourceComponent.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/CleanUpAudioSourceSystem.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/StartAudioSourceLoadingSystem.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/AudioSourcePluginIntegrationTests.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/CreateAudioSourceSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/StartAudioClipLoadingSystemShould.cs
Labels: no QA needed

#249 feat: avatar shape sdk component
  Explorer/Assets/DCL/AvatarRendering/Wearables/Components/BodyShape.cs
  Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef
  Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Components.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Components/SDKAvatarShapeComponent.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Components/SDKAvatarShapeComponent.cs.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShape.Tests.asmref
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShape.Tests.asmref.meta
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShapeHandlerSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShapeHandlerSystemShould.cs.meta
  Explorer/Assets/DCL/SDKComponents/DCL.SDKComponents.asmdef
  Explorer/Assets/DCL/Utilities/WorldProxy.cs
  Explorer/Assets/DCL/Utilities/WorldProxy.cs.meta
  Explorer/Assets/Scripts/ECS/Unity/ColorComponent/ColorExtensions.cs
  Explorer/Assets/Scripts/ECS/Unity/ECS.Unity.asmdef
  Explorer/Assets/Scripts/ECS/Unity/Tests/ECS.Unity.Tests.asmdef
  Explorer/Assets/Scripts/Global/Dynamic/GlobalWorldFactory.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
Labels: no QA needed, feature

#262 fix: Initialize Stars Buffer only once to prevent leaks
  Explorer/Assets/DCL/SkyBox/Rendering/DCL_RenderPass_GenerateSkyBox.cs
Labels: no QA needed

#277 fix Global Plugins Settings
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Labels: bug, no QA needed

#279 chore: remove backward TextShape
  Explorer/Assets/DCL/SDKComponents/TextShape/Renderer/Factory/TextShapeRendererFactory.cs
Labels: bug, no QA needed
