Repository decentraland/unity-explorer, pull requests merged in 2024-12, with the labels that each got.

#2933 Fix: system info not being send
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs
Labels: no QA needed

#2942 fix: sdk avatar shape emotes
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs
  Explorer/Assets/DCL/SDKComponents/DCL.SDKComponents.asmdef
Labels: bug, sdk, force-build

#2980 Feat: added hover panel on map
  Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererChunkComponentsFactory.cs
  Explorer/Assets/DCL/MapRenderer/ConsumerUtils/MapRenderImage.cs
  Explorer/Assets/DCL/MapRenderer/MapCameraController/IMapInteractivityController.cs
  Explorer/Assets/DCL/MapRenderer/MapCameraController/MapCameraInteractivityController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryMarker/CategoryMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Clusters/ClusterMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/IMapLayerController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/IMapRendererMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents/LiveEventsMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/ParcelHighlight/ParcelHighlightMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/PlayerMarker/PlayerMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/SceneOfInterestMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarker/SearchResultMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/HotUserMarker.cs
  Explorer/Assets/DCL/MapRenderer/Tests/MapCameraController/MapCameraInteractivityControllerShould.cs
  Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab
  Explorer/Assets/DCL/Navmap/Assets/PlaceToast.prefab
  Explorer/Assets/DCL/Navmap/NavmapBus/INavmapBus.cs
  Explorer/Assets/DCL/Navmap/NavmapBus/SharedNavmapBus.cs
  Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs
  Explorer/Assets/DCL/Navmap/PlaceInfoToastController.cs
  Explorer/Assets/DCL/Navmap/PlaceInfoToastView.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Labels: no QA needed, no review

#2991 fix: rework of map panel section
  Explorer/Assets/AddressableAssetsData/AssetGroups/Essentials.asset
  Explorer/Assets/DCL/MapRenderer/MapCameraController/MapCameraInteractivityController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/SatelliteAtlas/SatelliteChunkController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoriesEnum.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarkersController.cs
  Explorer/Assets/DCL/MapRenderer/OceanShader/DCLMap_basecolor2.png
  Explorer/Assets/DCL/MapRenderer/OceanShader/DCLMap_basecolor2.png.meta
  Explorer/Assets/DCL/MapRenderer/OceanShader/DCLMap_height2.png
  Explorer/Assets/DCL/MapRenderer/OceanShader/DCLMap_height2.png.meta
  Explorer/Assets/DCL/MapRenderer/OceanShader/MapOcean.mat
  Explorer/Assets/DCL/MapRenderer/Textures/GenericPin.png
  Explorer/Assets/DCL/MapRenderer/Textures/GenericPinFocused.png
  Explorer/Assets/DCL/MapRenderer/Textures/ParcelSelector.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinArt.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinBusiness.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinCasino.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinCrypto.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinEducation.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinFashion.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinFavourite.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinGames.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinMusic.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinShop.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinSocial.png
  Explorer/Assets/DCL/MapRenderer/Textures/PinSports.png
  Explorer/Assets/DCL/Navmap/Assets/CategoriesFilter.prefab
  Explorer/Assets/DCL/Navmap/Assets/CategoryToggle.prefab
  Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab
  Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab
  Explorer/Assets/DCL/Navmap/CategoryFilterController.cs
  Explorer/Assets/DCL/Navmap/INavmapCommand.cs
  Explorer/Assets/DCL/Navmap/NavmapBus/INavmapBus.cs
  Explorer/Assets/DCL/Navmap/NavmapBus/NavmapSearchPlaceSorting.cs
  Explorer/Assets/DCL/Navmap/NavmapBus/SharedNavmapBus.cs
  Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs
  Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs
  Explorer/Assets/DCL/Navmap/PlacesAndEventsPanelController.cs
  Explorer/Assets/DCL/Navmap/PlacesAndEventsPanelView.cs
  Explorer/Assets/DCL/Navmap/ScriptableObjects.meta
  Explorer/Assets/DCL/Navmap/ScriptableObjects/CategoryMappingSO.cs
  Explorer/Assets/DCL/Navmap/ScriptableObjects/CategoryMappingSO.cs.meta
  Explorer/Assets/DCL/Navmap/ScriptableObjects/MapCategoryIconMapping.asset
  Explorer/Assets/DCL/Navmap/ScriptableObjects/MapCategoryIconMapping.asset.meta
  Explorer/Assets/DCL/Navmap/SearchFiltersView.cs
  Explorer/Assets/DCL/Navmap/SearchForPlaceAndShowResultsCommand.cs
  Explorer/Assets/DCL/Navmap/SearchResultPanelController.cs
  Explorer/Assets/DCL/Navmap/ShowEventInfoCommand.cs
  Explorer/Assets/DCL/Navmap/ShowPlaceInfoCommand.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
  Explorer/Assets/DCL/UI/SearchBar/SearchBarView.cs
Labels: no QA needed, no review

#3011 Feat: camera reel - navmap integration
  Explorer/Assets/DCL/Editor/EntityBrowserWindow.cs.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab
  Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs
  Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab
  Explorer/Assets/DCL/Navmap/Navmap.asmdef
  Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs
  Explorer/Assets/DCL/Navmap/PlaceInfoPanelView.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Labels: no QA needed

#2907 feat: sdk ui enter-leave pointer events
  Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UITransformComponent.cs
  Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIPointerEventsSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/Extensions.cs
Labels: sdk, force-build

#3019 chore: camera-reel - change share to X message
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Labels: no QA needed

#3021 Enhance: Immutable entry for IReadOnlyEntityParticipantTable
  Explorer/Assets/DCL/Multiplayer/Profiles/Tables/EntityParticipantTable.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Tables/IReadOnlyEntityParticipantTable.cs
Labels: 3-low
