Repository decentraland/unity-explorer, pull requests merged in 2024-08, with the labels that each got.

#1575 fix: local scene development hot reload
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/SceneSharedContainer.cs
  Explorer/Assets/Scripts/SceneRuntime/Factory/SceneRuntimeFactory.cs
Labels: bug, no QA needed, sdk

#1645 fix: on-chain emotes definition & refactor of wearables
  Explorer/Assets/DCL/AvatarRendering/Emotes/Emote.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests.meta
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/DCL.Emotes.Tests.asmref
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/DCL.Emotes.Tests.asmref.meta
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/EmoteShould.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/EmoteShould.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Components/IAvatarAttachment.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Wearable.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/WearableShould.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/WearableShould.cs.meta
  Explorer/Assets/DCL/Passport/Modules/EquippedItems_PassportModuleController.cs
Labels: no QA needed

#1546 feat: local scene development js console
  Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/NullRoomHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/NullRoomHub.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/Diagnostics.asmdef
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/DiagnosticsContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/LocalSceneDevelopmentReportHandler.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/LocalSceneDevelopmentReportHandler.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHub.cs
  Explorer/Assets/Plugins/CommandTerminal.meta
  Explorer/Assets/Plugins/CommandTerminal/ConsoleBuffer.cs
  Explorer/Assets/Plugins/CommandTerminal/ConsoleBuffer.cs.meta
  Explorer/Assets/Plugins/CommandTerminal/LocalSceneTerminal.asmdef
  Explorer/Assets/Plugins/CommandTerminal/LocalSceneTerminal.asmdef.meta
  Explorer/Assets/Plugins/CommandTerminal/LocalSceneTerminal.cs
  Explorer/Assets/Plugins/CommandTerminal/LocalSceneTerminal.cs.meta
  Explorer/Assets/Plugins/CommandTerminal/Resources.meta
  Explorer/Assets/Plugins/CommandTerminal/Resources/LocalSceneTerminal.prefab
  Explorer/Assets/Plugins/CommandTerminal/Resources/LocalSceneTerminal.prefab.meta
  Explorer/Assets/Scripts/Global/Dynamic/ApplicationParametersParser.cs
  Explorer/Assets/Scripts/Global/Dynamic/ApplicationParametersParser.cs.meta
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/Scripts/SceneRunner/Scene/Tests/MockedReportScope.cs
Labels: no QA needed, feature, sdk

#1711 fix: map pins and minimap issues
  Explorer/Assets/DCL/MapRenderer/Addressables/PinMarkerObject.prefab
  Explorer/Assets/DCL/MapRenderer/Addressables/PinMarkerObject_Destination Variant.prefab
  Explorer/Assets/DCL/MapRenderer/CommonBehavior/MapMarkerPoolableBehavior.cs
  Explorer/Assets/DCL/MapRenderer/ConsumerUtils/MapRenderImage.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/IPinMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerObject.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinSelectedShadowAnimation.anim
  Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinSelectedShadowAnimation.anim.meta
  Explorer/Assets/DCL/MapRenderer/MapPath/Destination_MapPinAnimationElipse.png
  Explorer/Assets/DCL/MapRenderer/MapPath/Destination_MapPinAnimationElipse.png.meta
  Explorer/Assets/DCL/MapRenderer/MapPath/MapPathController.cs
  Explorer/Assets/DCL/MapRenderer/MapPath/MapPathRenderer.cs
  Explorer/Assets/DCL/MapRenderer/MapPath/PinMarkerHelper.cs
  Explorer/Assets/DCL/Minimap/Assets/MinimapPinMarkerObject.prefab
  Explorer/Assets/DCL/Navmap/Assets/DestinationInfoElement.prefab
  Explorer/Assets/DCL/Navmap/Assets/FloatingPanel.prefab
  Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab
  Explorer/Assets/DCL/Navmap/FloatingPanelController.cs
  Explorer/Assets/DCL/UI/Assets/UserNameElement.prefab
  Explorer/Assets/DCL/UI/Assets/UserWalletAddressElement.prefab
  Explorer/Assets/DCL/UI/Profile/ProfileElements/ProfileSectionController.cs
  Explorer/Assets/DCL/UI/Profile/ProfileElements/UserNameElement.cs
  Explorer/Assets/DCL/UI/Profile/ProfileElements/UserNameElementController.cs
  Explorer/Assets/DCL/UI/Profile/ProfileElements/UserWalletAddressElementController.cs
  Explorer/Assets/DCL/UI/Profile/ProfileMenuController.cs
  Explorer/Assets/DCL/UI/Sidebar/ProfileMenuView.prefab
Labels: force-build

#1773 style: update modals UI
  Explorer/Assets/DCL/ChangeRealmPrompt/Assets/ChangeRealmPrompt.prefab
  Explorer/Assets/DCL/ExternalUrlPrompt/Assets/ExternalUrlPrompt.prefab
  Explorer/Assets/DCL/NftPrompt/Assets/NftPrompt.prefab
  Explorer/Assets/DCL/TeleportPrompt/Assets/TeleportPrompt.prefab
  Explorer/Assets/Textures/Common/Container24RectBottom.png
  Explorer/Assets/Textures/Common/Container24RectBottom.png.meta
Labels: no QA needed

#1726 chore: update deep link detection for explorer launcher
  Explorer/Assets/Scripts/Global/ApplicationParametersParser.cs
  Explorer/Assets/Scripts/Global/Tests/EditMode/RealmLaunchSettingsShould.cs
  Explorer/ProjectSettings/ProjectSettings.asset
Labels: no QA needed, sdk, force-build

#1640 fix: unity cloud build cache improvements
  .github/workflows/build-release-weekly.yml
  .github/workflows/build-unitycloud.yml
  .github/workflows/pr-closure.yml
  scripts/cloudbuild/build.py
Labels: no QA needed

#1859 fix: deep link null param skip
  Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs
Labels: no QA needed, sdk

#1902 fix: cleaning up unity target on PR closure
  .github/workflows/pr-closure.yml
Labels: no QA needed

#1901 chore: separate build target for release build
  .github/workflows/build-release-weekly.yml
  scripts/cloudbuild/build.py
Labels: no QA needed

#1941 chore: add validation for branch name to avoid special characters
  scripts/cloudbuild/build.py
Labels: no QA needed

#1943 chore: support for clean build in unity cloud
  .github/workflows/build-unitycloud.yml
  scripts/cloudbuild/build.py
Labels: no QA needed

#1946 fix: unreliable sdk colliders initialization
  Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs
  Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs
Labels: bug, no QA needed, sdk
