Repository decentraland/unity-explorer, pull requests merged in 2024-10, with the labels that each got.

#2248 fix: NRE in MovementBadgesSystem
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs
Labels: no QA needed

#2232 fix: profiles deduplication
  Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs
  Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Rooms/GateKeeperSceneRoom.cs
  Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Rooms/IGateKeeperSceneRoom.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/ConnectiveRoom.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/RemotePosesRoomDisplay.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugRoomsSystem.cs
  Explorer/Assets/DCL/Multiplayer/Movement/Systems/MultiplayerMovementDebugSystem.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Announcements/RemoteAnnouncement.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/DCL.Multiplayer.Profiles.asmdef
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/DebounceRemoteMetadata.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/DebounceRemoteMetadata.cs.meta
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/DebounceRemotePoses.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/IRemoteMetadata.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/IRemoteMetadata.cs.meta
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/IRemotePoses.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemoteMetadata.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemoteMetadata.cs.meta
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemoteMetadataExtensions.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemoteMetadataExtensions.cs.meta
  Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemotePoses.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/RemoteProfiles/RemoteProfiles.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/LogRemoveIntentions.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/Systems/MultiplayerProfilesSystem.cs
  Explorer/Assets/DCL/Passport/Passport.asmdef
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/PluginSystem/Global/MultiplayerMovementPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/MultiplayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs
  Explorer/Assets/DCL/Profiles/Components/GetProfileIntention.cs
  Explorer/Assets/DCL/Profiles/MemoryProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/IProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/LogProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs
  Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef
  Explorer/Assets/DCL/Tests/PlayMode/DCL.PlayMode.Tests.asmdef
  Explorer/Assets/DCL/UI/Profile/ProfileElements/ProfileSectionController.cs
  Explorer/Assets/DCL/UI/Profile/ProfileElements/ProfileWidgetController.cs
  Explorer/Assets/DCL/UI/Profile/ProfileElements/UI.ProfileElements.asmdef
  Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
  Explorer/Assets/DCL/UI/Sidebar/UI.Sidebar.asmdef
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/SceneSharedContainer.cs
  Explorer/Assets/Scripts/Global/Tests/PlayMode/IntegrationTestsSuite.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs
  Explorer/Assets/Scripts/SceneRunner/Tests/SceneFacadeShould.cs
  Explorer/Assets/Scripts/SceneRunner/Tests/SceneFactoryShould.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/Players/PlayersWrap.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/UserIdentityApi/UserIdentityApiWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/ISceneRuntime.cs
  Explorer/Assets/Scripts/SceneRuntime/SceneRuntime.asmdef
  Explorer/Packages/packages-lock.json
Labels: 0-critical

#2246 Chore: default memory cap and settings for it
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/ISystemMemory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/ISystemMemory.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/ISystemMemoryCap.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/ISystemMemoryCap.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/MemoryBudget.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/StandaloneSystemMemory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/StandaloneSystemMemory.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/SystemMemoryCap.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Memory/SystemMemoryCap.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/Tests/MemoryBudgetProviderShould.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
  Explorer/Assets/DCL/PluginSystem/Global/StaticSettings.cs
  Explorer/Assets/DCL/Settings/Configuration/DropdownModuleBinding.cs
  Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset
  Explorer/Assets/DCL/Settings/Configuration/SettingsModuleBindings.cs
  Explorer/Assets/DCL/Settings/Configuration/SliderModuleBinding.cs
  Explorer/Assets/DCL/Settings/Configuration/ToggleModuleBinding.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/EnvironmentDistanceSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MemoryLimitSettingController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MemoryLimitSettingController.cs.meta
  Explorer/Assets/DCL/Settings/SettingsController.cs
  Explorer/Assets/DevLogs.preset
  Explorer/Assets/DevLogs.preset.meta
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapAnalyticsDecorator.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/IBootstrap.cs
  Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/Global/Tests/PlayMode/IntegrationTestsSuite.cs
  Explorer/DCL.Optimization.csproj.DotSettings
Labels: clean-build

#2352 fix: removed origin header from get requests
  Explorer/Assets/DCL/WebRequests/GenericDownloadHandlerUtils.cs
Labels: no QA needed

#2285 chore: support for dev branch
  .github/workflows/build-release-weekly.yml
  .github/workflows/build-unitycloud.yml
  .github/workflows/create-page-release-weekly.yml
  .github/workflows/test.yml
Labels: no QA needed

#2367 chore: dev branch changes
  .github/workflows/auto-label-issues.yml
  .github/workflows/build-Mac-il2cpp.yml
  .github/workflows/build-Windows-il2cpp.yml
  .github/workflows/build-profile-nightly.yml
  .github/workflows/build-release-main-page.yml
  .github/workflows/build-release-main.yml
  .github/workflows/build-unitycloud.yml
Labels: no QA needed

#2316 fix: sdk hot reload content mappings update + landscape
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/ECSReloadScene.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/IReloadScene.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/IScenesCache.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopmentController.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneLifeCycle.asmdef
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/UnloadSceneSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/UnloadSceneSystemShould.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/GlobalWorldFactory.cs
  Explorer/Assets/Scripts/Global/Dynamic/IGlobalRealmController.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
Labels: bug, 1-high, sdk

#2384 Fix: analytics system info
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs
Labels: no QA needed

#2377 style: increase reward background opacity
  Explorer/Assets/DCL/RewardPanel/Assets/RewardPanel.prefab
  Explorer/Assets/Textures/BackpackPanel/NFTDefaultIcon.png
Labels: enhancement, ui

#2430 fix: 50 plus gltf entities scene not loading locally
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
Labels: bug

#2460 chore: sync main to dev
  Explorer/Assets/DCL/SDKComponents/MediaStream/OpenMediaPromise.cs
  Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs
  Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
Labels: no QA needed

#2461 chore: updated the auto assign config
  .github/auto_assign_config.yml
Labels: no QA needed

#2380 Skybox revision
  Explorer/Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  Explorer/Assets/AddressableAssetsData/Windows/addressables_content_state.bin.meta
  Explorer/Assets/DCL/Quality/Quality Settings.asset
  Explorer/Assets/DCL/StylizedSkybox/Materials/GenesisSkybox.mat
  Explorer/Assets/DCL/StylizedSkybox/Prefabs/SkyboxController.prefab
  Explorer/Assets/DCL/UI/LoadingSpinner/M_ChargeBarV2.mat
  Explorer/Assets/Plugins/RustEthereum/sign-server/Cargo.lock.meta
  Explorer/Assets/Plugins/RustSegment/rust-segment/Cargo.lock.meta
  Explorer/Assets/Scenes/Main.unity
  Explorer/ProjectSettings/QualitySettings.asset
Labels: do not merge

#2468 chore: adjust minimum camera distance for main avatar visibility
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs
Labels: bug

#2506 fix: SDK input modifier effect persistence after teleport
  Explorer/Assets/DCL/PluginSystem/World/InputModifierPlugin.cs
  Explorer/Assets/DCL/SDKComponents/InputModifier/Systems/InputModifierHandlerSystem.cs
Labels: bug, 1-high, sdk

#2482 chore: move alpha_texture from PBRMaterial to UnlitMaterial
  Explorer/Assets/Protocol/DecentralandProtocol/Material.gen.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/Components/MaterialData.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/MaterialReference/BasicShapeMaterial.mat
  Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/CreateBasicMaterialSystem.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/CreatePBRMaterialSystem.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/Tests/CreateBasicMaterialSystemShould.cs
  Explorer/Assets/Scripts/ECS/Unity/Materials/Tests/LoadMaterialFromCacheSystemShould.cs
  scripts/package-lock.json
  scripts/package.json
Labels: tech debt

#2474 fix: unreliable 'playing' video event
  Explorer/Assets/DCL/SDKComponents/MediaStream/Components/MediaPlayerComponent.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
Labels: bug, sdk

#2546 Chore: temporarly disable performance analytics
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/PerformanceAnalyticsSystem.cs
Labels: no QA needed

#2541 fix: raw gltf external dependencies deeper path
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs
Labels: bug, sdk

#2580 fix: wrong tag version on dev
  .github/workflows/build-unitycloud.yml
Labels: no QA needed

#2563 fix: sdk video player SEEK + VS_ERROR video event
  Explorer/Assets/DCL/SDKComponents/MediaStream/Components/MediaPlayerComponent.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerExtensions.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
  Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs
  Explorer/Assets/DCL/WebRequests/WebRequestUtils.cs
Labels: bug, sdk
