Repository decentraland/unity-explorer, pull requests merged in 2024-09, with the labels that each got.

#1955 chore: update build-release-weekly.yml
  .github/workflows/build-release-weekly.yml
Labels: no QA needed

#1958 Fix: livekit intricacies
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs
  Explorer/Assets/DCL/ParcelsService/TeleportController.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus/SDKMessageBusCommsAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Tests/CommunicationControllerAPIImplementationShould.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Tests/Tests.asmdef
  Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs
  Explorer/Assets/Scripts/SceneRunner/SceneInstanceDeps.cs
Labels: no QA needed

#2029 chore: input modifier polish
  Explorer/Assets/DCL/SDKComponents/InputModifier/Systems/InputModifierHandlerSystem.cs
Labels: no QA needed

#2041 fix: deep link parsing macos patch
  Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs
  Explorer/Assets/Scripts/Global/Tests/EditMode/RealmLaunchSettingsShould.cs
Labels: no QA needed, 1-high, sdk

#2044 chore: fix localdevelopment with remote assetbundles
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Systems/PrepareGltfAssetLoadingSystem.cs
  Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Tests/PrepareGltfAssetLoadingSystemShould.cs
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/Global/Tests/PlayMode/IntegrationTestsSuite.cs
Labels: no QA needed

#1030 feat: sdk other players transform propagation
  Explorer/Assets/DCL/Character/CharacterMotion/Systems/WriteMainPlayerTransformSystem.cs
  Explorer/Assets/DCL/Character/CharacterMotion/Systems/WriteMainPlayerTransformSystem.cs.meta
  Explorer/Assets/DCL/Character/Plugin/CharacterContainer.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerTransformPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerTransformPropagationSystem.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WritePlayerTransformSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WritePlayerTransformSystem.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PropagateTransformTest.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PropagateTransformTest.cs.meta
  Explorer/Assets/DCL/PluginSystem/Global/MultiplayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MultiplayerPlugin.cs
  Explorer/Assets/DCL/SDKComponents/Tween/Components/CustomTweener/CustomTweenerImpl.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/Components/Transform/SDKTransform.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/Components/Transform/SDKTransformSerializer.cs
  Explorer/Assets/Scripts/ECS/TestSuite/ECS.TestSuite.asmdef
  Explorer/Assets/Scripts/ECS/TestSuite/EcsTestsUtils.cs
  Explorer/Assets/Scripts/ECS/Unity/Transforms/ExposedTransformUtils.cs
  Explorer/Assets/Scripts/ECS/Unity/Transforms/Tests/UpdateTransformSystemShould.cs
  Explorer/Assets/Scripts/SceneRunner/Scene/ISceneFacade.cs
Labels: no QA needed, sdk

#2095 fix: sdk hot reload models caching
  Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Systems/PrepareGltfAssetLoadingSystem.cs
Labels: no QA needed, sdk

#2058 chore: sdk camera control minor iteration
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/MainCameraSystem.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Tests/EditMode/MainCameraSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Tests/EditMode/VirtualCameraUtilsShould.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/VirtualCameraUtils.cs
  Explorer/Assets/Protocol/DecentralandProtocol/CameraTransition.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/MainCamera.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/VirtualCamera.gen.cs
  scripts/package-lock.json
  scripts/package.json
Labels: sdk

#2115 chore: updated test reporting action
  .github/workflows/test.yml
Labels: no QA needed

#2171 chore: add support for clean-build label
  .github/workflows/build-unitycloud.yml
Labels: no QA needed
