Repository decentraland/unity-explorer, pull requests merged in 2024-11, with the labels that each got.

#2672 Feat: camera reel storage services
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/InWorldCamera.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/AssemblyInfo.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/AssemblyInfo.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelImagesMetadataRemoteDatabase.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelImagesMetadataRemoteDatabase.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelRemoteStorageService.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelRemoteStorageService.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelS3BucketScreenshotsStorage.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelS3BucketScreenshotsStorage.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/DCL.CameraReelStorageService.asmdef
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/DCL.CameraReelStorageService.asmdef.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelImagesMetadataDatabase.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelImagesMetadataDatabase.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelScreenshotsStorage.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelScreenshotsStorage.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelStorageService.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelStorageService.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground/CameraReelRemoteServicesManualTest.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground/CameraReelRemoteServicesManualTest.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground/CameraReelStoragePlayground.unity
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground/CameraReelStoragePlayground.unity.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/CameraReelResponses.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/CameraReelResponses.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/CameraReelStorageStatus.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/CameraReelStorageStatus.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/ScreenshotMetadata.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Schemas/ScreenshotMetadata.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Tests.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Tests/CameraReelStorageServiceTests.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Tests/CameraReelStorageServiceTests.cs.meta
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Tests/DCL.CameraReelStorage.EditModeTests.asmref
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Tests/DCL.CameraReelStorage.EditModeTests.asmref.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Textures/Genesis_TX.png.meta
  Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef
  Explorer/Assets/DCL/WebRequests/GenericDownloadHandlerUtils.cs
  Explorer/Assets/DCL/WebRequests/SignedWebRequestControllerExtensions.cs
  Explorer/Assets/DCL/WebRequests/SignedWebRequestControllerExtensions.cs.meta
  Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs
  Explorer/DCL.CameraReelStorageService.csproj.DotSettings
Labels: no QA needed

#2709 chore: fetch commit hash
  .github/actions/version/action.yml
Labels: no QA needed, do not merge

#2651 feat: sdk pointer event toggle highlight
  Explorer/Assets/DCL/Interaction/Systems/ProcessPointerEventsSystem.cs
  Explorer/Assets/Protocol/DecentralandProtocol/PointerEvents.gen.cs
  scripts/package-lock.json
  scripts/package.json
Labels: feature, sdk

#2075 feat: support local gltf v3
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/DCL/WebRequests/Analytics/WebRequestsContainer.cs
  Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DisposableTexture.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DisposableTexture.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltfDownloadResult.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltfDownloadResult.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltfValidator.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltfValidator.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/TextureDownloadResult.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/TextureDownloadResult.cs.meta
  Explorer/Assets/Scripts/Global/StaticContainer.cs
Labels: feature, tech debt

#2715 chore: add workflow to automatically upload latest build to epic store
  .github/workflows/upload-build-epic-store.yml
Labels: no QA needed

#2735 fix: sdk video event time propagation
  Explorer/Assets/DCL/SDKComponents/MediaStream/Components/MediaPlayerComponent.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
Labels: bug, 1-high, sdk

#2781 fix: use short version for release builds
  .github/actions/version/action.yml
  .github/workflows/build-release-main.yml
  .github/workflows/build-unitycloud.yml
Labels: no QA needed

#2783 fix: remove deprecated hub usage in workflows
  .github/workflows/auto-sync-main-to-dev.yml
  .github/workflows/create-release-branch.yml
Labels: no QA needed

#2774 chore: updating the build process to support epic release builds
  .github/workflows/build-release-main-page.yml
  .github/workflows/build-release-main.yml
  .github/workflows/build-unitycloud.yml
  .github/workflows/upload-build-epic-store.yml
  scripts/cloudbuild/build.py
Labels: no QA needed

#2768 chore: keep lod until scene loaded
  Explorer/Assets/DCL/LOD/Settings/ILODSettingsAsset.cs
  Explorer/Assets/DCL/LOD/Settings/LODSettingsAsset.cs
  Explorer/Assets/DCL/LOD/Systems/UpdateVisualSceneStateSystem.cs
  Explorer/Assets/DCL/LOD/Systems/VisualSceneStateResolver.cs
  Explorer/Assets/DCL/LOD/Tests/EditMode/ResolveVisualSceneStateSystemShould.cs
  Explorer/Assets/DCL/LOD/Tests/EditMode/UpdateVisualSceneStateSystemShould.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerCRDTEntitiesHandlerSystemShould.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerProfileDataPropagationSystemShould.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/TransformsPlugin.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Components/VisualSceneState.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/SceneLODInfoExtensions.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/GatherGltfAssetsSystem.cs
  Explorer/Assets/Scripts/SceneRunner/ECSWorld/ECSWorldFactory.cs
  Explorer/Assets/Scripts/SceneRunner/Scene/PersistentEntities.cs
Labels: force-build

#2819 chore: add more debug for s3 upload workflow
  .github/workflows/s3-latest-release.yml
Labels: no QA needed

#2863 fix: include correct commit hash in PR builds
  .github/actions/version/action.yml
  .github/workflows/build-unitycloud.yml
Labels: no QA needed

#2742 fix: sdk avatar shape
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarLoaderSystem.cs
  Explorer/Assets/DCL/Character/CharacterMotion/Systems/RotateCharacterSystem.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/PlayerMarker/PlayerMarkerController.cs
  Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/UsersMarkersHotAreaController.cs
  Explorer/Assets/DCL/Minimap/Minimap.asmdef
  Explorer/Assets/DCL/Minimap/MinimapController.cs
  Explorer/Assets/DCL/Multiplayer/Movement/Systems/RemotePlayersMovementSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerTransformPropagationSystem.cs
  Explorer/Assets/DCL/NameTags/NametagView.cs
  Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShapeHandlerSystemShould.cs
  Explorer/Assets/Scripts/ECS/Unity/Tests/ECS.Unity.Tests.asmdef
Labels: bug, sdk

#2909 chore: correct video event error propagation on freeze check
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
Labels: bug, force-build
