Repository decentraland/unity-explorer, pull requests merged in 2024-06, with the labels that each got.

#1186 fix: SignedFetch does not work
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs
  Explorer/Assets/StreamingAssets/Js/Modules/SignedFetch.js
Labels: no QA needed

#1208 fix: SignedFetch does not work (II)
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs
  Explorer/Assets/StreamingAssets/Js/Modules/SignedFetch.js
Labels: no QA needed

#1212 fix: The fetch API for POST requests always fails
  Explorer/Assets/StreamingAssets/Js/Init.js
  Explorer/Assets/StreamingAssets/Js/Modules/FetchApi.js
Labels: no QA needed

#1275 fix tips stucking
  Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenController.cs
Labels: bug

#1216 fix: introduce developer artificial delay for testing purposes
  Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineSettingsSystem.cs
  Explorer/Assets/DCL/Input/Systems/UpdateShowHideUIInputSystem.cs
  Explorer/Assets/DCL/LOD/Systems/LODContainer.cs
  Explorer/Assets/DCL/LOD/Systems/LODDebugToolsSystem.cs
  Explorer/Assets/DCL/LOD/Systems/LODPlugin.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/DebugContainerBuilder.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/DebugWidgetBuilder.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/IDebugContainerBuilder.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/NullDebugContainerBuilder.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/NullDebugContainerBuilder.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilities.asmdef
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Declarations/DebugFloatFieldDef.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Declarations/DebugToggleDef.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/UIBindings/DebugWidgetVisibilityBinding.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/UIBindings/PersistentElementBinding.cs
  Explorer/Assets/DCL/PluginSystem/Global/CharacterCameraPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/InputPlugin.cs
  Explorer/Assets/DCL/PluginSystem/PluginSettingsContainer.cs
  Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/PlayMode/SDKAudioSourcesAutomatedTests.cs
  Explorer/Assets/DCL/Tests/PlayMode/DCL.PlayMode.Tests.asmdef
  Explorer/Assets/DCL/WebRequests/Analytics/Plugin/ShowWebRequestsAnalyticsSystem.cs
  Explorer/Assets/DCL/WebRequests/Analytics/WebRequestsContainer.cs
  Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs
  Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs.meta
  Explorer/Assets/DCL/WebRequests/IWebRequestController.cs
  Explorer/Assets/DCL/WebRequests/WebRequestController.cs
  Explorer/Assets/Scenes/Main.unity
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/DebugPanelChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldParams.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldSettings.cs
  Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/Scripts/Global/Static/StaticSceneLauncher.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFacade.cs
  Explorer/Assets/Scripts/Utility/Multithreading/ExecuteOnMainThreadScope.cs
  Explorer/Assets/Scripts/Utility/Multithreading/MultithreadingUtility.cs
  Explorer/Assets/Scripts/Utility/Storage/PersistentSetting.cs
  Explorer/Assets/Scripts/Utility/UIToolkit/VisualElementsExtensions.cs
Labels: feature

#1251 Feat: debug components command
  Explorer/Assets/DCL/Chat/ChatCommandsHandler.cs
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/Commands.meta
  Explorer/Assets/DCL/Chat/Commands/IChatCommand.cs
  Explorer/Assets/DCL/Chat/Commands/IChatCommand.cs.meta
  Explorer/Assets/DCL/Chat/History.meta
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs.meta
  Explorer/Assets/DCL/Chat/History/IChatHistory.cs
  Explorer/Assets/DCL/Chat/History/IChatHistory.cs.meta
  Explorer/Assets/DCL/Chat/MessageBus/ChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs
  Explorer/Assets/DCL/Minimap/MinimapController.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Declarations/DebugHintDef.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/MinimapPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WorldInfoPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WorldInfoPlugin.cs.meta
  Explorer/Assets/DCL/PluginSystem/World/Dependencies/ECSWorldSingletonSharedDependencies.cs
  Explorer/Assets/DCL/SDKComponents/Billboard/System/BillboardSystem.cs
  Explorer/Assets/DCL/SDKComponents/Billboard/Tests/BillboardTest.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/Components/Transform/SDKTransform.cs
  Explorer/Assets/Scripts/ECS/Unity/Transforms/Components/TransformComponent.cs
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ClearChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ClearChatCommand.cs.meta
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/DebugPanelChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ShowEntityInfoChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ShowEntityInfoChatCommand.cs.meta
  Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/TeleportToChatCommand.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/IWorldInfoHub.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/IWorldInfoHub.cs.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/LocationBasedWorldInfoHub.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/LocationBasedWorldInfoHub.cs.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/WorldInfoHub.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging/Hub/WorldInfoHub.cs.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/IWorldInfo.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging/IWorldInfo.cs.meta
  Explorer/Assets/Scripts/SceneRunner/Debugging/WorldInfo.cs
  Explorer/Assets/Scripts/SceneRunner/Debugging/WorldInfo.cs.meta
  Explorer/Assets/Scripts/SceneRunner/ECSWorld/ECSWorldFactory.cs
  Explorer/Assets/Scripts/SceneRunner/Mapping.meta
  Explorer/Assets/Scripts/SceneRunner/Mapping/ISceneMapping.cs
  Explorer/Assets/Scripts/SceneRunner/Mapping/ISceneMapping.cs.meta
  Explorer/Assets/Scripts/SceneRunner/Mapping/SceneMapping.cs
  Explorer/Assets/Scripts/SceneRunner/Mapping/SceneMapping.cs.meta
Labels: enhancement, feature
