Repository decentraland/unity-explorer, pull requests merged in 2024-05, with the labels that each got.

#1008 fix: AvatarBase and AvatarEquippedData by correcting Profile.IsDirty reset
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarLoaderSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerProfileDataPropagationSystemShould.cs
  Explorer/Assets/DCL/PluginSystem/Global/ProfilePlugin.cs
  Explorer/Assets/DCL/Profiles/Components/Profile.cs
Labels: bug, no QA needed, sdk

#1047 Fix: test fix for emotes and backpack issues
  Explorer/Assets/DCL/AvatarRendering/Wearables/ECSThumbnailProvider.cs
Labels: force-build

#1053 fix: the fetch api module was not working correctly
  Explorer/Assets/StreamingAssets/Js/Init.js
Labels: no QA needed

#1061 fix: the fetch api module was not working correctly (II)
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SimpleFetchApiImplementation.cs
Labels: no QA needed

#1058 chore: reduce allocations livekit
  Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Pipe/LogMessagePipe.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/DebounceRoomDisplay.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/DebounceRoomDisplay.cs.meta
  Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugRoomsSystem.cs
  Explorer/Assets/DCL/Multiplayer/Movement/Systems/PlayerMovementNetSendSystem.cs
Labels: optimization

#1095 fix: Player Identity Data component propagation
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/AvatarEmoteCommandPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEmoteCommandSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEquippedDataSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WritePlayerIdentityDataSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteSDKAvatarBaseSystem.cs
Labels: no QA needed, sdk

#1082 fix: [WebSocketApi.js] fix the access to our WebSocket implementation
  Explorer/Assets/StreamingAssets/Js/Modules/WebSocketApi.js
Labels: no QA needed

#1153 chore: add sorting to categories for Report Handling
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Settings/Editor/CategorySeverityMatrixDrawer.cs
Labels: no QA needed

#662 feat: sdk observables layer
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/AvatarEmoteCommandPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEmoteCommandSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEquippedDataSystem.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/CRDT.ECS.Bridge.asmdef
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationControllerHub.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus/SDKMessageBusCommsAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus/SDKMessageBusCommsAPIImplementation.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/EngineAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/JsModulesImplementation.asmdef
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SDKObservableEventsEngineAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SDKObservableEventsEngineAPIImplementation.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Tests/EngineAPIImplementationShould.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/IOutgoingCRDTMessagesProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/OutgoingCRDTMessagesProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/Tests/OutgoingCRTDMessagesProviderShould.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/ISharedPoolsProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/PoolableSDKObservableEventArray.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/PoolableSDKObservableEventArray.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/SharedPoolsProvider.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs
  Explorer/Assets/Scripts/SceneRunner/SceneInstanceDeps.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/ISDKMessageBusCommsControllerAPI.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/ISDKMessageBusCommsControllerAPI.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/SDKMessageBusCommsControllerAPIWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/SDKMessageBusCommsControllerAPIWrapper.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/EngineApiWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.asmdef
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.asmdef.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ISDKObservableEventsEngineApi.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ISDKObservableEventsEngineApi.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/SDKObservableEventsEngineApiWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/SDKObservableEventsEngineApiWrapper.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ScriptableSDKObservableEventArray.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ScriptableSDKObservableEventArray.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/ISceneRuntime.cs
  Explorer/Assets/Scripts/SceneRuntime/SceneRuntime.asmdef
  Explorer/Assets/Scripts/SceneRuntime/SceneRuntimeImpl.cs
  Explorer/Assets/StreamingAssets/Js/Modules/CommunicationsController.js
  Explorer/Assets/StreamingAssets/Js/Modules/EngineApi.js
Labels: sdk

#1157 fix: revert "feat: sdk observables layer (#662)"
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/AvatarEmoteCommandPropagationSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEmoteCommandSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEquippedDataSystem.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/CRDT.ECS.Bridge.asmdef
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationControllerHub.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus/SDKMessageBusCommsAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/SDKMessageBus/SDKMessageBusCommsAPIImplementation.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/EngineAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/JsModulesImplementation.asmdef
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SDKObservableEventsEngineAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SDKObservableEventsEngineAPIImplementation.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Tests/EngineAPIImplementationShould.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/IOutgoingCRDTMessagesProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/OutgoingCRDTMessagesProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/Tests/OutgoingCRTDMessagesProviderShould.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/ISharedPoolsProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/PoolableSDKObservableEventArray.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/PoolableSDKObservableEventArray.cs.meta
  Explorer/Assets/Scripts/CrdtEcsBridge/PoolsProviders/SharedPoolsProvider.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs
  Explorer/Assets/Scripts/SceneRunner/SceneInstanceDeps.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/ISDKMessageBusCommsControllerAPI.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/ISDKMessageBusCommsControllerAPI.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/SDKMessageBusCommsControllerAPIWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/CommunicationsControllerApi/SDKMessageBus/SDKMessageBusCommsControllerAPIWrapper.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/EngineApiWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.asmdef
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.asmdef.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/Events/SDKObservableEvents.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ISDKObservableEventsEngineApi.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ISDKObservableEventsEngineApi.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/SDKObservableEventsEngineApiWrapper.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/SDKObservableEventsEngineApiWrapper.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ScriptableSDKObservableEventArray.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApi/SDKObservableEvents/ScriptableSDKObservableEventArray.cs.meta
  Explorer/Assets/Scripts/SceneRuntime/ISceneRuntime.cs
  Explorer/Assets/Scripts/SceneRuntime/SceneRuntime.asmdef
  Explorer/Assets/Scripts/SceneRuntime/SceneRuntimeImpl.cs
  Explorer/Assets/StreamingAssets/Js/Modules/CommunicationsController.js
  Explorer/Assets/StreamingAssets/Js/Modules/EngineApi.js
Labels: no QA needed

#1139 WearablePlugin - remove mutex
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/LoadEmoteAudioClipSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/LoadEmotesByPointersSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/LoadOwnedEmotesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/LoadWearableAssetBundleManifestSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/LoadWearablesByParamSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/LoadWearablesDTOByPointersSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/LoadWearableByParamSystemShould.cs
  Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/ProfilePlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WearablePlugin.cs
  Explorer/Assets/DCL/Profiles/Systems/LoadProfileSystem.cs
Labels: no QA needed

#1177 fix: interactions from outside scenes
  Explorer/Assets/DCL/Interaction/PlayerOriginated/Tests/WritePointerEventResultsSystemShould.cs
  Explorer/Assets/DCL/Interaction/Systems/InteractionHighlightSystem.cs
  Explorer/Assets/DCL/Interaction/Systems/WritePointerEventResultsSystem.cs
  Explorer/Assets/DCL/PluginSystem/World/InteractionPlugin.cs
Labels: optimization
