Repository decentraland/unity-explorer, pull requests merged in 2024-04, with the labels that each got.

#478 fix: missing scoped registry in package manager settings for animation sequencer package
  Explorer/ProjectSettings/PackageManagerSettings.asset
Labels: no QA needed

#496 fix: force save of project before build to force source generation
  Explorer/Assets/Editor/BuildScript.cs
Labels: no QA needed

#534 feat: create dropdown & slider views
  Explorer/Assets/DCL/UI/Assets/Dropdown.prefab
  Explorer/Assets/DCL/UI/Assets/Dropdown.prefab.meta
  Explorer/Assets/DCL/UI/Assets/Slider.prefab
  Explorer/Assets/DCL/UI/DropdownView.cs
  Explorer/Assets/DCL/UI/DropdownView.cs.meta
  Explorer/Assets/DCL/UI/SliderView.cs
  Explorer/Assets/DCL/UI/SliderView.cs.meta
Labels: no QA needed

#636 fix: nullref on DELETE crdt messages
  Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/OutgoingCRDTMessagesProvider.cs
Labels: no QA needed

#632 feat: sdk multiplayer PBPlayerIdentityData support
  Explorer/Assets/DCL/Multiplayer/Multiplayer.asmdef
  Explorer/Assets/DCL/Multiplayer/SDK.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Components.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Components/PlayerIdentityDataComponent.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Components/PlayerIdentityDataComponent.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Systems.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/PlayerComponentsHandlerSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/PlayerComponentsHandlerSystem.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/WritePlayerIdentityDataSystem.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Systems/WritePlayerIdentityDataSystem.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Tests.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/DCL.Multiplayer.SDK.Tests.asmref
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/DCL.Multiplayer.SDK.Tests.asmref.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerComponentsHandlerSystemShould.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerComponentsHandlerSystemShould.cs.meta
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/WritePlayerIdentityDataSystemShould.cs
  Explorer/Assets/DCL/Multiplayer/SDK/Tests/WritePlayerIdentityDataSystemShould.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PluginSystem/Global/MultiplayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MultiplayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MultiplayerPlugin.cs.meta
  Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/PlayMode/SDKAudioSourcesAutomatedTests.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/Components/SpecialEntitiesID.cs
  Explorer/Assets/Scripts/Global/ComponentsContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/ProtobufPartialClasses/IDirtyMarker.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneFacade.cs
  Explorer/Assets/Scripts/SceneRunner/Scene/ISceneFacade.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFacade.cs
  Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs
  Explorer/Assets/Scripts/SceneRunner/Tests/SceneFacadeShould.cs
Labels: no QA needed, sdk

#685 Terraning generator cleans cache
  Explorer/Assets/DCL/Landscape/Config/Editor/DCL.Landscape.Editor.asmdef
  Explorer/Assets/DCL/Landscape/Config/Editor/TerrainGeneratorTestEditor.cs
  Explorer/Assets/DCL/Landscape/Config/Editor/TerrainTools.cs
  Explorer/Assets/DCL/Landscape/Config/Editor/TerrainTools.cs.meta
  Explorer/Assets/DCL/Landscape/Config/Editor/csc.rsp
  Explorer/Assets/DCL/Landscape/Config/Editor/csc.rsp.meta
  Explorer/Assets/DCL/Landscape/TerrainGeneratorTest.cs
  Explorer/Assets/DCL/Landscape/Utils/TerrainGeneratorLocalCache.cs
  Explorer/Assets/DCL/Landscape/csc.rsp
  Explorer/Assets/DCL/Landscape/csc.rsp.meta
Labels: no QA needed

#698 fix: Medium quality settings gives invisible terrain
  Explorer/Assets/DCL/Quality/Quality Settings.asset
  Explorer/ProjectSettings/QualitySettings.asset
Labels: no QA needed

#750 Fix: scene radius limit
  Explorer/Assets/DCL/Character/Plugin/CharacterContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Gizmos/Plugin/GizmosWorldPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AnimatorPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AssetBundlesPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AssetsCollidersPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AudioSourcesPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AvatarAttachPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AvatarModifierAreaPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/BillboardPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/CameraModeAreaPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/CharacterTriggerAreaPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/IDCLWorldPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/InteractionPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MaterialWorldPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MediaPlayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MultiplayerPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/NFTShapePlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/PrimitivesRenderingPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/TextShapePlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/TexturesLoadingPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/TransformsPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/TweenPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/VisibilityPlugin.cs
  Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset
  Explorer/Assets/Scripts/ECS/Prioritization/Settings/RealmPartitionSettingsAsset.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadEmptySceneSystemLogic.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/LoadEmptySceneSystemShould.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/LoadEmptySceneSystemShould.cs.meta
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/GlobalWorldFactory.cs
  Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneData.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneFacade.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneMapping.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneMapping.cs.meta
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptyScenesWorld.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptyScenesWorld.cs.meta
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptyScenesWorldFactory.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptyScenesWorldFactory.cs.meta
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/IEmptyScenesWorldFactory.cs
  Explorer/Assets/Scripts/SceneRunner/EmptyScene/IEmptyScenesWorldFactory.cs.meta
  Explorer/Assets/Scripts/Utility/ParcelMathJobifiedHelper.cs
Labels: 0-critical

#768 fix: allocations
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs
Labels: no QA needed

#721 fix: output version
  .github/workflows/build-Windows-il2cpp.yml
Labels: force-build

#828 chore: added hover audio handler
  Explorer/Assets/DCL/Audio/HoverAudioHandler.cs
  Explorer/Assets/DCL/Audio/HoverAudioHandler.cs.meta
Labels: no QA needed
