Repository decentraland/unity-explorer, pull requests merged in 2025-07, with the labels that each got.

#4605 Shape: destroy cached sprite on clear and remove previous image while loading
  Explorer/Assets/DCL/UI/ImageController.cs
  Explorer/Assets/DCL/UI/ImageView.cs
  Explorer/Assets/DCL/UI/SpriteCache.cs
Labels: shape-up, clean-build

#4549 fix: invisible avatar on wearable hide list combination
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Helpers/AvatarWearableHide.cs
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Helpers/AvatarWearableHide.cs.meta
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarInstantiatorSystem.cs
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Tests/EditMode/AvatarHideShould.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearableComponentsUtils.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/ResolveWearablePromisesSystem.cs
  Explorer/Assets/DCL/Backpack/AvatarSection/AvatarSlotView.cs
  Explorer/Assets/DCL/Backpack/BackpackInfoPanel/HideCategoriesController.cs
  Explorer/Assets/DCL/Backpack/BackpackSlotsController.cs
Labels: ai-review

#4658 [SHAPE-UP] Communities Fix (Pictures with transparent background can overlap the load image icon in community creation)
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CommunityCreationWizard.prefab
Labels: shape-up

#4666 [SHAPE-UP] Communities (Manage cancellations properly)
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerMemberListHelper.cs
  Explorer/Assets/DCL/Chat/ChatUserStateUpdater.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
Labels: shape-up

#4513 fix: avpro performance
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Systems/CreateMaterialSystemBase.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Textures/Utils/VideoTextureUtils.cs
  Explorer/Assets/DCL/Quality/Runtime/QualityLevelController.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/DCL.MediaPlayer.asmdef
  Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerCustomPool.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/InitializeVideoPlayerMaterialRequest.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/InitializeVideoPlayerMaterialRequest.cs.meta
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/InitializeVideoPlayerMaterialsSystem.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/InitializeVideoPlayerMaterialsSystem.cs.meta
  Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Component/InitializeNftVideoMaterialRequest.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Component/InitializeNftVideoMaterialRequest.cs.meta
  Explorer/Assets/DCL/SDKComponents/NFTShape/Frames/AbstractFrame.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Frames/MeshFrame.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Imported/Prefabs/NFTShapeLoader.prefab
  Explorer/Assets/DCL/SDKComponents/NFTShape/Renderer/INftShapeRenderer.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Renderer/NftShapeRenderer.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/System/LoadCycleNftShapeSystem.cs
  Explorer/Packages/packages-lock.json
Labels: ai-review

#4595 [SHAPE-UP] Communities (Creation Wizard polishments)
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CommunityCreationWizard.prefab
  Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CreateOrEditCommunityPanel.prefab
  Explorer/Assets/DCL/UI/Assets/SelectorButton.prefab
  Explorer/Assets/DCL/UI/Assets/SelectorButton.prefab.meta
  Explorer/Assets/DCL/UI/SelectorButton.meta
  Explorer/Assets/DCL/UI/SelectorButton/SelectorButtonOptionItemView.cs
  Explorer/Assets/DCL/UI/SelectorButton/SelectorButtonOptionItemView.cs.meta
  Explorer/Assets/DCL/UI/SelectorButton/SelectorButtonView.cs
  Explorer/Assets/DCL/UI/SelectorButton/SelectorButtonView.cs.meta
Labels: shape-up

#4671 [SHAPE-UP] Communities (Community browser and wizard null fixes)
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs
  Explorer/Assets/DCL/Communities/CommunitiesUtility.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityPlaceTag.cs
  Explorer/Assets/DCL/UI/ISpriteCache.cs
  Explorer/Assets/DCL/UI/SpriteCache.cs
Labels: shape-up

#4640 chore: constrain sdk vcam to scene bounds
  Explorer/Assets/DCL/Infrastructure/SceneRunner/Scene/ISceneData.cs
  Explorer/Assets/DCL/Infrastructure/Utility/ParcelMathHelper.cs
  Explorer/Assets/DCL/Interaction/Raycast/Systems/ExecuteRaycastSystem.cs
  Explorer/Assets/DCL/PluginSystem/World/MainCameraPlugin.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/MainCameraSystem.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/VirtualCameraSystem.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Tests/EditMode/MainCameraSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Tests/PlayMode/VirtualCameraSystemShould.cs
Labels: bug, 2-medium

#4685 [SHAPE-UP] Communities (Open community card after creation)
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
Labels: shape-up

#4675 ImageController removed from Communities UI classes
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser.prefab
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListItemView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlaceCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
  Explorer/Assets/DCL/Communities/EventInfo/EventInfoController.cs
  Explorer/Assets/DCL/Communities/EventInfo/EventInfoView.cs
  Explorer/Assets/DCL/Communities/ThumbnailLoader.cs
  Explorer/Assets/DCL/Communities/ThumbnailLoader.cs.meta
  Explorer/Assets/DCL/UI/Communities/CommunityTitleView.cs
  Explorer/Assets/DCL/UI/ImageController.cs
  Explorer/Assets/DCL/UI/ImageView.cs
Labels: enhancement, shape-up, clean-build

#4701 chore: skip enforce approval when no QA needed label present
  .github/workflows/enforce-group-approvals.yml
Labels: no QA needed

#4687 fix: GPUI asset creation
  Explorer/Packages/packages-lock.json
Labels: no QA needed, no review

#4709 [Communities Polishing] Several visual polishments in the Creation Wizard
  Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CreateOrEditCommunityPanel.prefab
  Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/PlaceTag.prefab
  Explorer/Assets/DCL/UI/Assets/SelectorButton.prefab
  Explorer/Assets/DCL/UI/SelectorButton/SelectorButtonView.cs
Labels: shape-up

#4727 [Communities Polishing] Show/Hide members counter in the Community Result Card (under new Feature Flag)
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
Labels: shape-up

#4743 [Communities Polishing] Remove FakeCommunitiesDataProvider & ICommunitiesDataProvider
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerMemberListHelper.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs.meta
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Labels: no QA needed, shape-up

#4741 [Communities Polishing] Add the owner name + Live tag in the results community cards
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_RightSection.prefab
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs
Labels: no QA needed, shape-up

#4732 fix: Correct usage of .today environment
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/IDecentralandUrlsSource.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/RealmController.cs
Labels: force-build

#4738 feat: Communities Voice Chat Orchestrator
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/VoiceChatPlugin.cs
  Explorer/Assets/DCL/VoiceChat/CallButtonController.cs
  Explorer/Assets/DCL/VoiceChat/CommunitiesVoiceChatController.cs
  Explorer/Assets/DCL/VoiceChat/CommunitiesVoiceChatController.cs.meta
  Explorer/Assets/DCL/VoiceChat/IVoiceChatCallStatusService.cs
  Explorer/Assets/DCL/VoiceChat/PrivateVoiceChatController.cs
  Explorer/Assets/DCL/VoiceChat/PrivateVoiceChatController.cs.meta
  Explorer/Assets/DCL/VoiceChat/Services/RPCPrivateVoiceChatService.cs
  Explorer/Assets/DCL/VoiceChat/Services/RPCPrivateVoiceChatService.cs.meta
  Explorer/Assets/DCL/VoiceChat/VoiceChatCallStatusService.cs
  Explorer/Assets/DCL/VoiceChat/VoiceChatOrchestrator.cs
  Explorer/Assets/DCL/VoiceChat/VoiceChatOrchestrator.cs.meta
Labels: no QA needed

#4758 fix: [Communities Polishing] Rename "isVerified" by "hasClaimedName" in GetUserCommunitiesResponse DTO
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs
Labels: no QA needed, shape-up

#4796 chore: update generate-ignore-warnings.sh
  scripts/generate-ignore-warnings.sh
Labels: force-build

#4807 Revert "feat: features registry singleton"
  Explorer/Assets/DCL/Chat/Chat.asmdef
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/Commands/KillPortableExperienceChatCommand.cs
  Explorer/Assets/DCL/Chat/Commands/LoadPortableExperienceChatCommand.cs
  Explorer/Assets/DCL/Chat/MessageBus/DCL.Chat.MessageBus.asmdef
  Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs
  Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs.meta
  Explorer/Assets/DCL/ExplorePanel/ExplorePanel.asmdef
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs
  Explorer/Assets/DCL/FeatureFlags/CommunitiesFeatureProvider.cs.meta
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
  Explorer/Assets/DCL/FeatureFlags/FeaturesRegistry.cs
  Explorer/Assets/DCL/FeatureFlags/FeaturesRegistry.cs.meta
  Explorer/Assets/DCL/FeatureFlags/IFeatureProvider.cs
  Explorer/Assets/DCL/FeatureFlags/IFeatureProvider.cs.meta
  Explorer/Assets/DCL/Friends/DCL.Friends.asmdef
  Explorer/Assets/DCL/Friends/FriendsConnectivityStatusTracker.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/FriendsPanelController.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendSectionController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/BootstrapAnalyticsDecorator.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/BootstrapContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/IBootstrap.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/DCL/Infrastructure/Global/Tests/PlayMode/IntegrationTestsSuite.cs
  Explorer/Assets/DCL/Infrastructure/MVC/MVCFacade/MVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/MapPins/Systems/MapPinLoaderSystem.cs
  Explorer/Assets/DCL/Notifications/Notifications.asmdef
  Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs
  Explorer/Assets/DCL/Passport/Passport.asmdef
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/FriendsContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/MainUIPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/MultiplayerMovementPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/MapPinPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/NFTShapePlugin.cs
  Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
  Explorer/Assets/DCL/Settings/Configuration/DropdownModuleBinding.cs
  Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.cs
  Explorer/Assets/DCL/Settings/Configuration/SettingsModuleBindings.cs
  Explorer/Assets/DCL/Settings/Configuration/SliderModuleBinding.cs
  Explorer/Assets/DCL/Settings/Configuration/ToggleModuleBinding.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/VoiceChatVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/SettingsController.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/DCL.UI.GenericContextMenu.Controllers.asmdef
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuController.cs
  Explorer/Assets/DCL/UI/MainUIContainer/MainUIController.cs
  Explorer/Assets/DCL/UI/MainUIContainer/MainUi.asmdef
  Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/DCL.UI.SharedSpaceManager.asmdef
  Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/SharedSpaceManager.cs
  Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
Labels: no QA needed

#4787 feat: [Communities Polishing] Close Community Chat
  Explorer/Assets/DCL/Chat/Assets/ChatConversationsToolbarViewTooltip.prefab
  Explorer/Assets/DCL/Chat/Chat.asmdef
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/CommunityChatConversationsToolbarViewItem.cs
  Explorer/Assets/DCL/Prefs/DCLPrefKeys.cs
Labels: shape-up

#4754 feat: sdk GltfNodeModifiers component support
  Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearablePolymorphicBehaviour.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/GLTFData.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Systems/CreateGltfAssetFromRawGltfSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/CleanUpGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/FinalizeGltfContainerLoadingSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ResetGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/CleanUpGltfContainerSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/ResetGltfContainerSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Components.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Components/GltfNode.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Components/GltfNode.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Components/GltfNodeModifiers.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Components/GltfNodeModifiers.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/CleanupGltfNodeModifierSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/CleanupGltfNodeModifierSystem.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/GltfNodeModifierSystemBase.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/GltfNodeModifierSystemBase.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/SetupGltfNodeModifierSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/SetupGltfNodeModifierSystem.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/UpdateGltfNodeModifierSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Systems/UpdateGltfNodeModifierSystem.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/CleanupGltfNodeModifierSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/CleanupGltfNodeModifierSystemShould.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/GltfNodeModifiers.Tests.asmref
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/GltfNodeModifiers.Tests.asmref.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/SetupGltfNodeModifierSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/SetupGltfNodeModifierSystemShould.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/UpdateGltfNodeModifierSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GltfNodeModifiers/Tests/UpdateGltfNodeModifierSystemShould.cs.meta
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/ReleaseMaterial.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Systems/ApplyMaterialSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Systems/ResetMaterialSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Tests/ApplyMaterialSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Tests/ResetMaterialSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Materials/Tests/StartMaterialLoadingSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Textures/Components/VideoTextureConsumer.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Textures/Utils/VideoTextureUtils.cs
  Explorer/Assets/DCL/Infrastructure/Global/ComponentsContainer.cs
  Explorer/Assets/DCL/Infrastructure/ProtobufPartialClasses/IDirtyMarker.cs
  Explorer/Assets/DCL/PluginSystem/Global/GlobalGLTFLoadingPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/Protocol/DecentralandProtocol/ComponentID.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/GltfNodeModifiers.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/GltfNodeModifiers.gen.cs.meta
  scripts/package-lock.json
  scripts/package.json
Labels: feature, sdk

#4888 fix: Remove LIVE mark from the community cards
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs
Labels: shape-up

#4881 fix: Save the closed community chats in local storage by wallet
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Prefs/DCLPrefKeys.cs
Labels: shape-up

#4899 fix: Communities button animation
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/CommunitiesTab/Hover.anim
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/CommunitiesTab/Unhover.anim
Labels: no QA needed

#4907 Fixed: Nearby chat appears with an offline warning (#4824)
  Explorer/Assets/DCL/Chat/ChatController.cs
Labels: bug, ui
