Repository decentraland/unity-explorer, pull requests merged in 2025-08, with the labels that each got.

#4922 Chore: extend sentrylogs for WebRequestExceptions
  Explorer/Assets/DCL/WebRequests/WebRequestController.cs
Labels: no QA needed

#4947 Fixed: When clicking on private chat toolbar icons their colors turn wrong
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
Labels: bug, ui

#5041 chore: debug widget average fps banner
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugViewsCatalog.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Declarations/AverageFpsBannerDef.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Declarations/AverageFpsBannerDef.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/AverageFpsBanner.uxml
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/AverageFpsBanner.uxml.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/DebugUtilitiesStyle.uss
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/AverageFpsBannerElement.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/AverageFpsBannerElement.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs
  Explorer/Assets/Scenes/Main.unity
Labels: enhancement, sdk

#5068 Fixed: Logging in and out makes the community chats disappear (#4990)
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/UserConnectivityInfoProvider.cs
Labels: bug

#5120 Private communities: Invitations context menu
  Explorer/Assets/DCL/Chat/_Refactor/ChatTitleBar/ChatTitlebarPresenter.cs
  Explorer/Assets/DCL/Communities/Communities.asmdef
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/CommunityMemberListContextMenuConfiguration.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/CommunityMemberListContextMenuSettings.asset
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetInvitableCommunityListResponse.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/MVC/MVCFacade/MVC.MVCManagerMenusAccessFacade.asmdef
  Explorer/Assets/DCL/Infrastructure/MVC/MVCFacade/MVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/Notifications/Assets/NotificationIcons.asset
  Explorer/Assets/DCL/Notifications/NewNotification/NewNotificationController.cs
  Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs
  Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/InvitationToCommunitySentNotification.cs
  Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/InvitationToCommunitySentNotification.cs.meta
  Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/NotificationType.cs
  Explorer/Assets/DCL/Passport/Passport.asmdef
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/Passport/PassportView.cs
  Explorer/Assets/DCL/Passport/Prefabs/Passport.prefab
  Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities.meta
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/CommunityInvitationContextMenuButtonHandler.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/CommunityInvitationContextMenuButtonHandler.cs.meta
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/DCL.UI.GenericContextMenu.Controllers.Communities.asmdef
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/DCL.UI.GenericContextMenu.Controllers.Communities.asmdef.meta
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/DCL.UI.GenericContextMenu.Controllers.asmdef
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuController.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuSettings.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/Configs/SubMenuContextMenuButtonSettings.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/ControlsContainerView.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/GenericContextMenuScrollableButtonListView.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/GenericContextMenuSubMenuButtonView.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/ControlsPoolManager.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/GenericContextMenuController.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/ControlsContainer.prefab
  Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/GenericUserProfileContextMenuSettings.asset
  Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/SubMenuButton.prefab
  Explorer/Assets/DCL/UI/GenericContextMenuParameter/GenericContextMenu.cs
  Explorer/Assets/Textures/Common/CommunitiesIcn.png
  Explorer/Assets/Textures/Common/CommunitiesIcn.png.meta
Labels: ui, shape-up

#5149 chore: test action improvements
  .github/workflows/test - manual.yml
  .github/workflows/test.yml
Labels: no QA needed

#5198 fix: using il2cpp windows target version for test.yml
  .github/workflows/test.yml
Labels: no QA needed
