Repository decentraland/unity-explorer, pull requests merged in 2025-04, with the labels that each got.

#3457 Don't allocate when downloading json
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs
  Explorer/Assets/DCL/Ipfs/SceneMetadata.cs
  Explorer/Assets/DCL/Utilities/Json.meta
  Explorer/Assets/DCL/Utilities/Json/IPreserveOriginalJson.cs
  Explorer/Assets/DCL/Utilities/Json/IPreserveOriginalJson.cs.meta
  Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJson.cs
  Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJson.cs.meta
  Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJsonConverter.cs
  Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJsonConverter.cs.meta
  Explorer/Assets/DCL/Utilities/UTF8Utility.cs
  Explorer/Assets/DCL/Utilities/UTF8Utility.cs.meta
  Explorer/Assets/DCL/WebRequests/GenericDownloadHandlerUtils.cs
  Explorer/Assets/DCL/WebRequests/WRThreadFlags.cs
Labels: force-build

#3815 add null checks
  Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
Labels: no QA needed

#3825 fix: scene reload missing entity alive check
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs
Labels: bug, 0-critical, sdk

#3748 fix: PBGltfContainer props update lost while GLTF is still loading
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ConfigureGltfContainerColliders.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ResetGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/LoadGltfContainerSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/SDKCollider.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
Labels: bug

#3881 fix: gltf collision layer update lost while loading (revisited)
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ConfigureGltfContainerColliders.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ResetGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/LoadGltfContainerSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/SDKCollider.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
Labels: bug, sdk

#3867 chore: sdk scene debug console minor improvements
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/DiagnosticsContainer.cs
  Explorer/Assets/Plugins/CommandTerminal/SceneDebugConsole.cs
Labels: enhancement, sdk

#3936 fix: sdk virtual camera rotating characters
  Explorer/Assets/DCL/PluginSystem/World/MainCameraPlugin.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/MainCameraSystem.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Tests/EditMode/MainCameraSystemShould.cs
  Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/VirtualCameraUtils.cs
Labels: bug, sdk

#3827 Local storage of the chat history (private conversations shape)
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs
  Explorer/Assets/DCL/Chat/ChatEntryView.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/History/ChatChannel.cs
  Explorer/Assets/DCL/Chat/History/ChatHistoryEncryptor.cs
  Explorer/Assets/DCL/Chat/History/ChatHistoryEncryptor.cs.meta
  Explorer/Assets/DCL/Chat/History/ChatHistorySerializer.cs
  Explorer/Assets/DCL/Chat/History/ChatHistorySerializer.cs.meta
  Explorer/Assets/DCL/Chat/History/ChatHistoryStorage.cs
  Explorer/Assets/DCL/Chat/History/ChatHistoryStorage.cs.meta
  Explorer/Assets/DCL/Chat/History/ChatMessage.cs
  Explorer/Assets/DCL/Chat/History/ChatMessageFactory.cs
  Explorer/Assets/DCL/Chat/History/ChatMessageFactory.cs.meta
  Explorer/Assets/DCL/Chat/History/DCL.Chat.History.asmdef
  Explorer/Assets/DCL/Chat/History/IChatHistory.cs
  Explorer/Assets/DCL/Chat/MessageBus/DCL.Chat.MessageBus.asmdef
  Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/MVC/WindowsStackManager/WindowStackManager.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/UI/InputSuggestions/InputSuggestionPanelView.cs
  Explorer/ProjectSettings/ProjectSettings.asset
Labels: feature, shape-up

#3937 New chat bubbles visibility setting
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/NameTags/NametagsData.cs
  Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/ChatAnalytics.cs
  Explorer/Assets/DCL/Settings/Configuration/DropdownModuleBinding.cs
  Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset
  Explorer/Assets/DCL/Settings/ModuleControllers/ChatBubblesVisibilityController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/ChatBubblesVisibilityController.cs.meta
  Explorer/Assets/DCL/Settings/Settings/ChatSettingsAsset.cs
Labels: feature, ui, shape-up

#3973 chore: update version in the readme
  README.md
Labels: no QA needed

#4016 fix: expose "current scene" in normal debug container
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs
Labels: force-build
