Repository decentraland/unity-explorer, pull requests merged in 2025-02, with the labels that each got.

#3257 feat: add direct parameter to context object to collect ip's
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DynamicCommonTraitsPlugin.cs
Labels: no QA needed

#3251 style: update 'external URL' copies and add buttons animations
  Explorer/Assets/DCL/ExternalUrlPrompt/Assets/ExternalUrlPrompt.prefab
Labels: ui

#3250 style: fix photos hover animation
  Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Assets/ThumbnailElement.prefab
  Explorer/Assets/DCL/InWorldCamera/Textures/SquaredOutline.png
  Explorer/Assets/DCL/InWorldCamera/Textures/SquaredOutline.png.meta
Labels: ui

#3227 Let Protobuf use optimized JavaScript types
  Explorer/Assets/Scripts/SceneRuntime/ModuleHub/SceneModuleHub.cs
Labels: clean-build

#3238 chore: sdk scene console disable auto-scrolling
  Explorer/Assets/Plugins/CommandTerminal/ConsoleBuffer.cs
  Explorer/Assets/Plugins/CommandTerminal/ConsoleBuffer.cs.meta
  Explorer/Assets/Plugins/CommandTerminal/Resources/SceneDebugConsole.prefab
  Explorer/Assets/Plugins/CommandTerminal/SceneDebugConsole.cs
Labels: enhancement, sdk

#3275 fix: 3089 - IDisposableTexture boxing
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DisposableTexture.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltfDownloadResult.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/TextureDownloadResult.cs
Labels: clean-build

#3270 chore: run tests on windows
  .github/workflows/test.yml
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Tests/Instantiate/AvatarInstantiatorSystemShould.cs
Labels: force-build

#3097 feat: preview unreleased wearable collections in backpack
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayConstants.cs
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayContainer.cs
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayContainerFactory.cs
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayHandler.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetOwnedEmotesFromRealmIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/EmbeddedEmotesData.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadOwnedEmotesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/Assets/AttachmentAssetBase.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/Components/IAttachmentsLoadingIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/DTO/AvatarAttachmentDTO.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/ILambdaResponse.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/Systems/Abstract/LoadElementsByIntentionSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Thumbnails/Tests/ResolveWearableThumbnailSystemShould.cs
  Explorer/Assets/DCL/AvatarRendering/Thumbnails/Utils/LoadThumbnailsUtils.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Intentions/GetWearableByParamIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/ECSWearablesProvider.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/DTO/WearableDTO.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearablePolymorphicBehaviour.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/IWearablesProvider.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeAssetBundleWearableLoadingSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeAssetBundleWearableLoadingSystem.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeRawWearableLoadingSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeRawWearableLoadingSystem.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeWearableLoadingSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeWearableLoadingSystemBase.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeWearableLoadingSystemBase.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/Load/LoadWearablesByParamSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/ResolveWearablePromisesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/ResolveWearablePromisesSystem.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/ResolveWearableByPointerSystemShould.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Wearables.asmdef
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/CommunicationData/URLHelpers/IURLBuilder.cs
  Explorer/Assets/DCL/PluginSystem/Global/DefaultTexturesContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WearablePlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
  Explorer/Assets/DCL/Utilities/TextureUtilities.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastDownloadProviderBase.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastDownloadProviderBase.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastDownloadStrategy.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastDownloadStrategy.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastGlobalDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastGlobalDownloadProvider.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastSceneDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastSceneDownloadProvider.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/IGLTFastDisposableDownloadProvider.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/DownloadProvider/IGLTFastDisposableDownloadProvider.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Tests/MultipleLoadSystemShould.cs
  Explorer/Assets/Scripts/Global/AppArgs/AppArgsFlags.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/GlobalWorldFactory.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs
Labels: feature

#3363 style: update slot empty state
  Explorer/Assets/DCL/Backpack/Assets/AvatarSlot.prefab
  Explorer/Assets/DCL/Backpack/Assets/EmoteSlotContainer.prefab
Labels: ui

#3369 chore: enable self-preview wearables outside backpack
  Explorer/Assets/DCL/Backpack/Backpack.asmdef
  Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs
  Explorer/Assets/DCL/Multiplayer/Profiles/BroadcastProfiles/EnsureSelfPublishedProfileBroadcast.cs
  Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/Profiles/MemoryProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/IProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/LogProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Self/ISelfProfile.cs
  Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs
  Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Labels: feature

#3379 chore: self-preview-builder-collections CSV support
  Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs
  Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs
  Explorer/Assets/DCL/PluginSystem/Global/DefaultTexturesContainer.cs
  Explorer/Assets/Scripts/Global/AppArgs/AppArgsFlags.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Labels: enhancement

#3409 Update ClearScript, switch Invoke to readonly ref struct scopes
  Explorer/Packages/packages-lock.json
Labels: force-build

#3438 fix: audio issue on first spawn
  Explorer/Assets/DCL/Audio/AudioMixerVolumesController.cs
Labels: force-build
