Repository decentraland/unity-explorer, pull requests merged in 2025-01, with the labels that each got.

#3047 chore: move analytics file to proper folder
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DCL.Analytics.asmdef
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/MVCManagerAnalyticsDecorator.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/AuthenticationScreenAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/ChatAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/DCL.Analytics.EventBased.asmdef
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/ExplorePanelAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PassportAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PhotoDetailAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PhotoDetailAnalytics.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/SupportAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/WalkedDistanceAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/AnalyticsPlugin.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs
Labels: no QA needed

#3020 feat: sky controlls panel
  Explorer/.gitignore
  Explorer/Assets/AddressableAssetsData/AssetGroups/Settings.asset
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Active.anim
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Active.anim.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Empty.anim
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Empty.anim.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Hover.anim
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Hover.anim.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/SkyButtonAnimatorController.controller
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/SkyButtonAnimatorController.controller.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/SkyButtonOverrideAnimatorController.overrideController
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/SkyButtonOverrideAnimatorController.overrideController.meta
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Unhover.anim
  Explorer/Assets/DCL/ExplorePanel/Assets/Animations/SkyButton/Unhover.anim.meta
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelView.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
  Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs
  Explorer/Assets/DCL/StylizedSkybox/Editor/SkyboxController_Editor.cs
  Explorer/Assets/DCL/StylizedSkybox/Prefabs/SkyboxController.prefab
  Explorer/Assets/DCL/StylizedSkybox/Scripts/Plugin/StylizedSkyboxPlugin.cs
  Explorer/Assets/DCL/StylizedSkybox/Scripts/SkyboxController.cs
  Explorer/Assets/DCL/StylizedSkybox/Scripts/StylizedSkyboxSettingsAsset.cs
  Explorer/Assets/DCL/StylizedSkybox/Scripts/StylizedSkyboxSettingsAsset.cs.meta
  Explorer/Assets/DCL/StylizedSkybox/StylizedSkybox.asmdef
  Explorer/Assets/DCL/StylizedSkybox/StylizedSkyboxSettings.asset
  Explorer/Assets/DCL/StylizedSkybox/StylizedSkyboxSettings.asset.meta
  Explorer/Assets/DCL/UI/Buttons/SimpleHoverableButton.cs
  Explorer/Assets/DCL/UI/Buttons/SimpleHoverableButton.cs.meta
  Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
  Explorer/Assets/DCL/UI/Sidebar/SidebarUI.BottomLayout.prefab
  Explorer/Assets/DCL/UI/Sidebar/SidebarUI.prefab
  Explorer/Assets/DCL/UI/Sidebar/SidebarView.cs
  Explorer/Assets/DCL/UI/Sidebar/SkyboxMenuView.prefab
  Explorer/Assets/DCL/UI/Sidebar/SkyboxMenuView.prefab.meta
  Explorer/Assets/DCL/UI/Sidebar/SkyboxWidget.prefab
  Explorer/Assets/DCL/UI/Sidebar/SkyboxWidget.prefab.meta
  Explorer/Assets/DCL/UI/Skybox.meta
  Explorer/Assets/DCL/UI/Skybox/SkyboxMenuController.cs
  Explorer/Assets/DCL/UI/Skybox/SkyboxMenuController.cs.meta
  Explorer/Assets/DCL/UI/Skybox/SkyboxMenuView.cs
  Explorer/Assets/DCL/UI/Skybox/SkyboxMenuView.cs.meta
  Explorer/Assets/DCL/UI/UI.asmdef
  Explorer/Assets/Scripts/Global/AppArgs/IAppArgs.cs
  Explorer/Assets/Scripts/Global/AppArgs/Tests/AppArgsTests.cs
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
  Explorer/Assets/Textures/ExplorePanel/SkyboxOffIcon.png
  Explorer/Assets/Textures/ExplorePanel/SkyboxOffIcon.png.meta
  Explorer/Assets/Textures/ExplorePanel/SkyboxOnIcon.png
  Explorer/Assets/Textures/ExplorePanel/SkyboxOnIcon.png.meta
Labels: clean-build

#3114 Incorporate Partial Downloading concept into `LoadSystemBase`
  Explorer/Assets/DCL/AvatarRendering/Loading/Systems/Abstract/LoadElementsByIntentionSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/Systems/Abstract/LoadElementsByPointersSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/Load/LoadWearableAssetBundleManifestSystem.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/PerformanceBudgeting/AcquiredBudget/IAcquiredBudget.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/PoolConstants.cs
  Explorer/Assets/DCL/Profiles/Systems/LoadProfileSystem.cs
  Explorer/Assets/DCL/WebRequests/PartialDownload/PartialDownloadingData.cs
  Explorer/Assets/DCL/WorldTime/WorldTimeProvider.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/RuntimeImplementation.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/GetAssetBundleIntention.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/LoadAssetBundleSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/AudioClips/LoadAudioClipSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/AssetPromise.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/CommonLoadingArguments.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/PartialLoadingState.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/PartialLoadingState.cs.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/StreamableLoadingState.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/AssetsLoadingUtility.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/LoadSystemBase.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/DeferredLoading/DeferredLoadingSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/NFTShapes/LoadNFTShapeSystem.cs
  Explorer/Assets/Scripts/ECS/StreamableLoading/PartialLoad.meta
  Explorer/Assets/Scripts/ECS/StreamableLoading/Textures/LoadTextureSystem.cs
Labels: no QA needed, no review

#3155 chore: add missing users to github review group
  .github/auto_assign_config.yml
Labels: no QA needed

#3153 fix: search bar shortcut block
  .gitignore
  Explorer/.gitignore
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs
  Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs
  Explorer/UserSettings/EditorUserSettings.asset
  Explorer/UserSettings/Search.index
  Explorer/UserSettings/Search.settings
Labels: clean-build

#3195 fix: ensure src of intention is compared against the component
  Explorer/Assets/Scripts/ECS/StreamableLoading/Textures/GetTextureIntention.cs
  Explorer/Assets/Scripts/ECS/Unity/Textures/Utils/TextureComponentUtils.cs
Labels: force-build, clean-build

#3189 chore: reduce terrain memory usage
  Explorer/Assets/DCL/Landscape/Config/NoiseData.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/BaseNoiseGenerator.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/CompositeNoiseGenerator.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/NoiseGenerator.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/NoiseGeneratorCache.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/NoiseNativeArrayProvider.cs
  Explorer/Assets/DCL/Landscape/NoiseGeneration/NoiseNativeArrayProvider.cs.meta
  Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
  Explorer/Assets/DCL/Landscape/Worlds/WorldTerrainGenerator.cs
Labels: force-build

#3008 feat: asset bundle fallback
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Playground/ScreenRecorderTester.cs
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/ScreencaptureCamera.asmdef
  Explorer/Assets/DCL/Ipfs/AssetBundleRegistryEnum.cs
  Explorer/Assets/DCL/Ipfs/AssetBundleRegistryEnum.cs.meta
  Explorer/Assets/DCL/Ipfs/DCL.Ipfs.asmdef
  Explorer/Assets/DCL/Ipfs/EntityDefinitionGeneric.cs
  Explorer/Assets/DCL/Ipfs/IIpfsRealm.cs
  Explorer/Assets/DCL/Ipfs/InvalidIpfsRealm.cs
  Explorer/Assets/DCL/Ipfs/IpfsRealm.cs
  Explorer/Assets/DCL/Ipfs/LocalIpfsRealm.cs
  Explorer/Assets/DCL/Ipfs/LogIpfsRealm.cs
  Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/SceneRoomMetaDataSource.cs
  Explorer/Assets/DCL/Profiles/DCL.Profiles.asmdef
  Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs
  Explorer/Assets/DCL/RealmNavigation/Container/RealmContainer.cs
  Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Assets/ConnectionStatus.prefab
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Assets/StatusEntry.prefab
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelController.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelView.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/StatusEntry/IStatusEntry.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionStatusBackplate.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionStatusBackplate.png.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI.ConnectionStatusPanel.asmdef
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/CurrentScene/CurrentSceneInfo.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/CurrentScene/ICurrentSceneInfo.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/IncreasingRadius/LoadPointersByIncreasingRadiusSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/LoadStaticPointersSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/ResolveStaticPointersSystem.cs
  Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/TestIpfsRealm.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/PortableExperiences/ECSPortableExperiencesController.cs
  Explorer/Assets/Scripts/Global/Dynamic/PortableExperiences/PortableExperiencesController.asmdef
  Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
Labels: force-build

#3205 chore: update character cam collision to include sdk physics layer
  Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab
Labels: enhancement, sdk, force-build

#3231 fix: always check for clean build label
  .github/workflows/build-unitycloud.yml
Labels: clean-build

#3181 feat: add crash detection analytics event
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/CrashDetector.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/CrashDetector.cs.meta
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/IAnalyticsController.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/IDebugContainerBuilder.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
Labels: clean-build

#3225 fix: allow nametag toggling in camera and fix UI toggling
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/InWorldCameraComponents.cs
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/InWorldCameraPlugin.cs
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/ToggleInWorldCameraActivitySystem.cs
  Explorer/Assets/DCL/Input/Systems/UpdateShowHideUIInputSystem.cs
  Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs
  Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions
  Explorer/Assets/DCL/PluginSystem/Global/InputPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs
  Explorer/Assets/Scenes/Main.unity
  Explorer/Assets/Scripts/Global/Dynamic/BootstrapAnalyticsDecorator.cs
  Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldParams.cs
  Explorer/Assets/Scripts/Global/Dynamic/IBootstrap.cs
  Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/Scripts/Global/StaticContainer.cs
  Explorer/Assets/Scripts/Global/Tests/PlayMode/IntegrationTestsSuite.cs
Labels: clean-build
