Repository decentraland/unity-explorer, pull requests merged in 2025-03, with the labels that each got.

#3328 feat: sdk movePlayerTo new avatar target param
  Explorer/Assets/Protocol/DecentralandProtocol/RestrictedActions.gen.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/IGlobalWorldActions.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/RestrictedActionsAPIImplementation.cs
  Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/Tests/RestrictedActionsAPIImplementationShould.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/IRestrictedActionsAPI.cs
  Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs
  Explorer/Assets/StreamingAssets/Js/Modules/RestrictedActions.js
  scripts/package-lock.json
  scripts/package.json
Labels: enhancement, feature, sdk

#3480 Fix: js code test
  Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef
  Explorer/Assets/Scripts/SceneRuntime/Factory/Tests/JsCodeDiskSerializerShould.cs
Labels: no QA needed

#3473 fix: sdk movePlayerTo() + sdk camera corrections
  Explorer/Assets/DCL/Character/CharacterCamera/CinemachineExtensions.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Components/CameraComponent.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineCameraInputSystem.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Systems/ControlCinemachineVirtualCameraSystem.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Systems/WriteCameraComponentsSystem.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Tests/ApplyCinemachineCameraInputSystemShould.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Tests/ApplyCinemachineCameraInputSystemShould.cs.meta
  Explorer/Assets/DCL/Character/CharacterCamera/Tests/CinemachineVirtualCameraSystemShould.cs
  Explorer/Assets/DCL/Character/CharacterMotion/Systems/RotateCharacterSystem.cs
  Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef
  Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs
Labels: bug

#3546 fix: missing texturefuse compression failure fallback
  Explorer/Assets/DCL/WebRequests/Texture/GetTextureWebRequest.cs
Labels: bug, sdk

#3551 fix: threadsafe pool
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/ThreadSafePool/ThreadSafeObjectPool.cs
Labels: no QA needed

#3563 fix: cinemachine not updating with CameraLookAt component
  Explorer/Assets/DCL/Character/CharacterCamera/Components/CameraComponent.cs
  Explorer/Assets/DCL/Character/CharacterCamera/Systems/UpdateCinemachineBrainSystem.cs
Labels: bug

#3505 Implement shell execute ourselves
  Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs
Labels: force-build

#3595 fix: local scene dev reload memory leak
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneLifeCycle.asmdef
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/GLTFData.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/GltfDownloadResult.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Systems/CreateGltfAssetFromAssetBundleSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Systems/CreateGltfAssetFromRawGltfSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/CleanUpGltfContainerSystem.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ProfilingCounters.cs
Labels: bug, sdk, memory-issue

#3583 fix: local scene dev mode analytics
  Explorer/Assets/DCL/Infrastructure/Global/AppArgs/AppArgsFlags.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/BootstrapContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DCL.Analytics.asmdef
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DynamicCommonTraitsPlugin.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs
Labels: analytics

#3632 fix: sdk local scene dev hot-reload
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Labels: bug, 0-critical, sdk

#3676 chore: landscape terrain toggling with app arg
  Explorer/Assets/DCL/Infrastructure/Global/AppArgs/AppArgsFlags.cs
  Explorer/Assets/DCL/Infrastructure/Global/AppArgs/IAppArgs.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs
  Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs
Labels: enhancement, sdk

#3705 fix: sdk avatar shape transform interpolation not using global pos
  Explorer/Assets/DCL/Character/CharacterMotion/Systems/SDKAvatarShapesMotionSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/Transforms/ExposedTransformUtils.cs
  Explorer/Assets/DCL/Infrastructure/Utility/ParcelMathHelper.cs
  Explorer/Assets/DCL/Interaction/Utility/RaycastUtils.cs
  Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs
  Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/UpdateAvatarShapeInterpolateMovementSystem.cs
Labels: bug, sdk

#3699 fix: unreleased wearables preview breaking with 2K texture resolution
  Explorer/Assets/DCL/Utilities/TextureUtilities.cs
Labels: bug

#3760 style: change thumbnails aspect ratio from 1:1 to 4:3 for map results cards
  Explorer/Assets/DCL/Navmap/Assets/EventEntry.prefab
  Explorer/Assets/DCL/Navmap/Assets/PlaceSearchEntry.prefab
Labels: enhancement, ui

#3609 Shape : Private Conversations - Chat LiveKit Room implementation + Starting conversations (lite)
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatTitlebarDefault.prefab
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs
  Explorer/Assets/DCL/Chat/ChatEventBus.cs
  Explorer/Assets/DCL/Chat/ChatEventBus.cs.meta
  Explorer/Assets/DCL/Chat/ChatInputBus.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/History/ChatChannel.cs
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs
  Explorer/Assets/DCL/Chat/History/ChatMessage.cs
  Explorer/Assets/DCL/Chat/History/IChatHistory.cs
  Explorer/Assets/DCL/Chat/InputBus/IChatEventBus.cs
  Explorer/Assets/DCL/Chat/InputBus/IChatEventBus.cs.meta
  Explorer/Assets/DCL/Chat/InputBus/IChatInputBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/IgnoreWithSymbolsChatMessageBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs
  Explorer/Assets/DCL/Friends/DCL.Friends.asmdef
  Explorer/Assets/DCL/Friends/UI/FriendPanel/FriendsPanelController.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendSectionController.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendsSectionDoubleCollectionController.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/Fixed/ChatConnectiveRoom.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/Fixed/ChatConnectiveRoom.cs.meta
  Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Hubs/IMessagePipesHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Hubs/MessagePipesHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/IRoomHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/NullRoomHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/RoomHub.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Rooms/RoomSource.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WorldInfoPlugin.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuController.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuSettings.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/GenericUserProfileContextMenuSettings.asset
  Explorer/Assets/DCL/UI/TextFormatter/HyperlinkTextFormatter.cs
  Explorer/Assets/DCL/UI/TextFormatter/ITextFormatter.cs
  Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs
  Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/Scripts/MVC/MVCFacade/MVCManagerMenusAccessFacade.cs
Labels: feature, ui, shape-up

#3764 fix: update MVFW tip
  Explorer/Assets/DCL/SceneLoadingScreens/Textures/MVFWImg.png
  Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Labels: ui
