Repository decentraland/unity-explorer, pull requests merged in 2025-05, with the labels that each got.

#3931 Chat metrics for private conversations
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/ChatAnalytics.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Playgrounds/AnalyticsConfiguration Playground.asset
Labels: no QA needed, shape-up, analytics

#4052 Feat: Add Delete chat history button to context menu (#4054)
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/Commands/ChatCommandsBus.cs
  Explorer/Assets/DCL/Chat/Commands/ClearChatCommand.cs
  Explorer/Assets/DCL/Chat/Commands/ClearChatCommand.cs.meta
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs
  Explorer/Assets/DCL/Chat/History/ChatHistoryStorage.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/MVC/MVCFacade/MVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/IMVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/ChatOptionsContextMenuController.cs
Labels: bug, ui

#4004 The chat UI stays while the panel is focused
  Explorer/Assets/DCL/Chat/Assets/Chat.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatInputBox.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarCloseButton.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerShowParams/ChatControllerShowParams.cs
  Explorer/Assets/DCL/Chat/ChatInputBoxElement.cs
  Explorer/Assets/DCL/Chat/ChatMemberListView.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/Commands/ChatCommandsBus.cs
  Explorer/Assets/DCL/Chat/Commands/ClearChatCommand.cs
  Explorer/Assets/DCL/Chat/Commands/ClearChatCommand.cs.meta
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs
  Explorer/Assets/DCL/Chat/History/ChatHistoryStorage.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/MVC/ControllerBase.cs
  Explorer/Assets/DCL/Infrastructure/MVC/MVCFacade/MVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/IMVCManagerMenusAccessFacade.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs
  Explorer/Assets/DCL/UI/CustomInputField/CustomInputField.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/ChatOptionsContextMenuController.cs
  Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/SharedSpaceManager.cs
  Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
Labels: enhancement, ui

#4025 chore: update debugging tools style
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/DebugContainer.uxml
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/DebugIcn.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Assets/ConnectionStatus.prefab
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionIcon.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionIcon.png.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionStatusBackplate.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionStatusPanelReference.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ConnectionStatusPanelReference.png.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/LinkIcon.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/ResetIcn.png.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/Tag.png
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/Textures/Tag.png.meta
  Explorer/Assets/Plugins/CommandTerminal/Resources/SceneDebugConsole.prefab
  Explorer/Assets/Plugins/CommandTerminal/SceneDebugConsole.cs
  Explorer/Assets/Textures/Common/ConsoleIcon.png
  Explorer/Assets/Textures/Common/ConsoleIcon.png.meta
Labels: enhancement

#4081 fix: [Marketplace Credits] Modify the call to set-email request to pass the new isCreditsWorkflow boolean param
  Explorer/Assets/DCL/MarketplaceCreditsAPIService/EmailSubscriptionBody.cs
  Explorer/Assets/DCL/MarketplaceCreditsAPIService/MarketplaceCreditsAPIClient.cs
Labels: no QA needed

#4086 Fix: Chat | Disappears completely after using Jump In from Online Friends panel (#3843)
  Explorer/Assets/DCL/Friends/UI/FriendPanel/FriendsPanelController.cs
Labels: bug

#4093 fix: sdk raycast returning outdated global positions instead of scene-relative
  Explorer/Assets/DCL/Interaction/Raycast/Systems/ExecuteRaycastSystem.cs
  Explorer/Assets/DCL/Interaction/Raycast/Tests/ExecuteRaycastSystemShould.cs
  Explorer/Assets/DCL/Interaction/Raycast/Tests/RaycastUtilsShould.cs
  Explorer/Assets/DCL/Interaction/Utility/RaycastUtils.cs
Labels: bug, 1-high, sdk

#3390 fix: scene emotes during local scene development
  Explorer/Assets/DCL/AvatarRendering/AvatarShape/UnityInterface/AvatarBase.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/EmoteReferences.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetSceneEmoteFromLocalSceneIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetSceneEmoteFromLocalSceneIntention.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetSceneEmoteFromRealmIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/IEmoteAssetIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/IEmoteAssetIntention.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/FinalizeEmoteLoadingSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadSceneEmotesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/EmotePlayer.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/FinalizeEmoteLoadingSystemShould.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/FinalizeEmoteLoadingSystemShould.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Loading/AssemblyInfo.cs
  Explorer/Assets/DCL/AvatarRendering/Loading/AssemblyInfo.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Loading/Assets/AttachmentAssetBase.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/IGlobalWorldActions.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/RestrictedActionsAPIImplementation.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/Tests/GlobalWorldActionsShould.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/Tests/GlobalWorldActionsShould.cs.meta
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/Tests/RestrictedActions.Tests.asmdef
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/DownloadProvider/GltFastDownloadStrategy.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/GetGLTFIntention.cs
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
  Explorer/Assets/DCL/Infrastructure/ECS/Unity/ECS.Unity.asmdef
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/GlobalWorldFactory.cs
  Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/WearablePlugin.cs
  Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef
Labels: feature, sdk, force-build

#4239 fix: check if tag exists before adding a new one on create a release page workflow
  .github/workflows/build-release-main-page.yml
Labels: no QA needed
