Repository decentraland/unity-explorer, pull requests merged in 2025-09, with the labels that each got.

#5249 fix: error on last attempt sprite cache
  Explorer/Assets/DCL/UI/SpriteCache.cs
Labels: no QA needed

#5283 Fix: Context menu is way to big when there's only one community appearing
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/UI/Communities/CommunityChatConversationContextMenuSettings.asset
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/CommunityInvitationContextMenuButtonHandler.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuController.cs
Labels: bug, ui

#5309 chore: builder wearables preview also show all wearables
  Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs
  Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteGridController.cs
Labels: enhancement, 1-high

#5265 feat: web requests monitor
  Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/Playground/CameraReelRemoteServicesManualTest.cs
  Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Playground/ScreenRecorderTester.cs
  Explorer/Assets/DCL/Infrastructure/ECS/REnum.dll
  Explorer/Assets/DCL/Infrastructure/ECS/REnumSourceGenerator.dll
  Explorer/Assets/DCL/Infrastructure/ECS/REnumSourceGenerator.dll.meta
  Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/Tests/LoadAssetBundlePartialSystemShould.cs
  Explorer/Assets/DCL/Infrastructure/ECS/TestSuite/TestWebRequestController.cs
  Explorer/Assets/DCL/Infrastructure/Global/AppArgs/AppArgsFlags.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs
  Explorer/Assets/DCL/Infrastructure/Global/Tests/PlayMode/IntegrationTestsSuite.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Demo/GateKeeperRoomPlayground.cs
  Explorer/Assets/DCL/Multiplayer/Connections/Demo/LocalSceneDevelopmentPlayground.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset
  Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef
  Explorer/Assets/DCL/PluginSystem/Global/DebugMenuPlugin.cs
  Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Demo/AllNftShapePlaygroundBoot.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Demo/MaterialsDemoWorld.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Demo/NFTShapeDemoWorld.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Demo/NftShapePlaygroundBoot.cs
  Explorer/Assets/DCL/SDKComponents/NFTShape/Demo/WarmUpSettingsNftShapeDemoWorld.cs
  Explorer/Assets/DCL/UI/DebugMenu/DCL.UI.DebugMenu.asmdef
  Explorer/Assets/DCL/UI/DebugMenu/DebugMenuController.cs
  Explorer/Assets/DCL/WebRequests/Analytics/Plugin/ShowWebRequestsAnalyticsSystem.cs
  Explorer/Assets/DCL/WebRequests/Analytics/Plugin/WebRequestsPlugin.cs
  Explorer/Assets/DCL/WebRequests/Analytics/WebRequestsContainer.cs
  Explorer/Assets/DCL/WebRequests/ChromeDevtool.meta
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/ChromeDevtoolProtocolClient.cs
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/ChromeDevtoolProtocolClient.cs.meta
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/CreatorHubBrowser.cs
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/CreatorHubBrowser.cs.meta
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/DCLLogger.cs
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/DCLLogger.cs.meta
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/NativeBrowser.cs
  Explorer/Assets/DCL/WebRequests/ChromeDevtool/NativeBrowser.cs.meta
  Explorer/Assets/DCL/WebRequests/DCL.WebRequests.asmdef
  Explorer/Assets/DCL/WebRequests/IWebRequestController.cs
  Explorer/Assets/DCL/WebRequests/RequestEnvelope.cs
  Explorer/Assets/DCL/WebRequests/WebRequestController.cs
  Explorer/Assets/DCL/WebRequests/WebRequestHeadersInfo.cs
  Explorer/Assets/Plugins/DclNativeProcesses/DCL.Native.Processes.asmdef
  Explorer/Assets/Plugins/DclNativeProcesses/DCLProcesses.dll
  Explorer/Assets/Plugins/DclNativeProcesses/DCLProcesses.exp
  Explorer/Assets/Plugins/DclNativeProcesses/DCLProcesses.lib
  Explorer/Assets/Plugins/DclNativeProcesses/DclProcessesNativeMethods.cs
  Explorer/Assets/Plugins/DclNativeProcesses/dcl_processes.c
  Explorer/Assets/Plugins/DclNativeProcesses/dcl_processes.h
  Explorer/Assets/Plugins/DclNativeProcesses/libDCLProcesses.dylib
  Explorer/Assets/Plugins/WindowsRegistry.meta
  Explorer/Assets/Plugins/WindowsRegistry/WindowsRegistry.asmdef
  Explorer/Assets/Plugins/WindowsRegistry/WindowsRegistry.asmdef.meta
  Explorer/Assets/Plugins/WindowsRegistry/WindowsRegistry.cs
  Explorer/Assets/Plugins/WindowsRegistry/WindowsRegistry.cs.meta
  Explorer/Packages/manifest.json
  Explorer/Packages/packages-lock.json
  Explorer/ProjectSettings/ProjectSettings.asset
Labels: clean-build

#5365 Move ProfileNameColorHelper to another library that has nothing to do with Profiles or UI
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerChatBubblesHelper.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Chat/_Refactor/ChatCommands/CreateMessageViewModelCommand.cs
  Explorer/Assets/DCL/Chat/_Refactor/ChatServices/ChatWorldBubbleService.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetCommunityInviteRequestResponse.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetCommunityMembersResponse.cs
  Explorer/Assets/DCL/Friends/RPCFriendsService.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/FriendProfileExtension.cs
  Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetail.asmdef
  Explorer/Assets/DCL/InWorldCamera/PhotoDetail/VisiblePersonController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
  Explorer/Assets/DCL/Notifications/NotificationEntry/FriendsNotificationView.cs
  Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs
  Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
  Explorer/Assets/DCL/UI/ProfileNameTooltipView.cs
  Explorer/Assets/DCL/Utilities/NameColorHelper.cs
  Explorer/Assets/DCL/Utilities/NameColorHelper.cs.meta
Labels: tech debt

#5351 Adapt pending classes to use NotificationsBusController as a singleton
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/PersistentFriendPanelOpenerController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs
  Explorer/Assets/DCL/Notifications/NewNotification/NewNotificationController.cs
  Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs
  Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/FriendsContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/MarketplaceCreditsPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/NotificationPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/RewardPanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs
  Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
Labels: tech debt, shape-up

#5285 chore: separate connection status panel from DebugMenu
  Explorer/Assets/AddressableAssetsData/AssetGroups/UI.asset
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/ConnectionStatusPanelPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/ConnectionStatusPanelPlugin.cs.meta
  Explorer/Assets/DCL/PluginSystem/Global/DebugMenuPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
  Explorer/Assets/DCL/PluginSystem/Global/MainUIPlugin.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionPanelView.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionPanelView.cs.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatus.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatus.cs.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelController.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelController.cs.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelUIDocument.prefab
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/ConnectionStatusPanelUIDocument.prefab.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI.ConnectionStatusPanel.asmdef
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI.ConnectionStatusPanel.asmdef.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/ConnectionStatusPanel.uss
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/ConnectionStatusPanel.uss.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/ConnectionStatusPanel.uxml
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/ConnectionStatusPanel.uxml.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/Elements.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/Elements/AssetBundleSceneStatusElement.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/Elements/AssetBundleSceneStatusElement.cs.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/Elements/ConnectionStatusElement.cs
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/UI/Elements/ConnectionStatusElement.cs.meta
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/csc.rsp
  Explorer/Assets/DCL/UI/ConnectionStatusPanel/csc.rsp.meta
  Explorer/Assets/DCL/UI/DebugMenu/ConnectionPanelView.cs
  Explorer/Assets/DCL/UI/DebugMenu/ConnectionPanelView.cs.meta
  Explorer/Assets/DCL/UI/DebugMenu/ConnectionStatus.cs.meta
  Explorer/Assets/DCL/UI/DebugMenu/DCL.UI.DebugMenu.asmdef
  Explorer/Assets/DCL/UI/DebugMenu/DebugMenuController.cs
  Explorer/Assets/DCL/UI/DebugMenu/UI/DebugMenu.uss
  Explorer/Assets/DCL/UI/DebugMenu/UI/DebugMenu.uxml
  Explorer/Assets/DCL/UI/DebugMenu/UI/Elements/ConnectionStatusElement.cs.meta
  Explorer/Assets/DCL/UI/MainUIContainer/MainUIController.cs
Labels: enhancement

#5608 chore: prevent running build on every label added
  .github/workflows/build-unitycloud.yml
Labels: no QA needed
