Repository decentraland/unity-explorer, pull requests merged in 2025-06, with the labels that each got.

#4321 [SHAPE-UP] Communities (GET Communities endpoint integration)
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs
  Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
  Explorer/Assets/DCL/Communities/Communities.asmdef
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/CommunityMemberRole.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs
  Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab
  Explorer/Assets/DCL/ExplorePanel/ExplorePanelView.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset
  Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Labels: shape-up

#4234 feat: cursor position info
  Explorer/Assets/DCL/Infrastructure/Global/ComponentsContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/StaticContainer.cs
  Explorer/Assets/DCL/Infrastructure/Global/Tests/PlayMode/IntegrationTestsSuite.cs
  Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef
  Explorer/Assets/DCL/PluginSystem/World/PrimaryPointerInfoPlugin.cs
  Explorer/Assets/DCL/PluginSystem/World/PrimaryPointerInfoPlugin.cs.meta
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo.meta
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo/PrimaryPointerInfo.asmdef
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo/PrimaryPointerInfo.asmdef.meta
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo/Systems.meta
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo/Systems/PrimaryPointerInfoSystem.cs
  Explorer/Assets/DCL/SDKComponents/PrimaryPointerInfo/Systems/PrimaryPointerInfoSystem.cs.meta
  Explorer/Assets/Protocol/DecentralandProtocol/ComponentID.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/InputAction.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/PrimaryPointerInfo.gen.cs
  Explorer/Assets/Protocol/DecentralandProtocol/PrimaryPointerInfo.gen.cs.meta
  scripts/package-lock.json
  scripts/package.json
Labels: clean-build

#4362 Fix: Sometimes profile pictures are not loading properly
  Explorer/Assets/DCL/Chat/ChatConversationsToolbarViewItem.cs
  Explorer/Assets/DCL/Chat/ChatMemberListViewItem.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/FriendPanelUserView.cs
  Explorer/Assets/DCL/Friends/UI/PushNotifications/FriendPushNotificationController.cs
  Explorer/Assets/DCL/Friends/UI/PushNotifications/FriendPushNotificationView.cs
  Explorer/Assets/DCL/Friends/UI/Requests/FriendRequestController.cs
  Explorer/Assets/DCL/Friends/UI/UnfriendConfirmationPopupController.cs
  Explorer/Assets/DCL/Friends/UI/UnfriendConfirmationPopupView.cs
  Explorer/Assets/DCL/InWorldCamera/PhotoDetail/VisiblePersonController.cs
  Explorer/Assets/DCL/Passport/PassportController.cs
  Explorer/Assets/DCL/Passport/PassportView.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/GenericContextMenuUserProfileView.cs
  Explorer/Assets/DCL/UI/InputSuggestions/ProfileInputSuggestionElement.cs
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfileSectionController.cs
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfileWidgetController.cs
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/SimpleProfileView.cs
Labels: bug, 1-high, ui

#4341 fix: rave mode
  Explorer/Assets/StreamingAssets/AssetBundles/lods/dcl/scene_texarray_ignore_mac
  Explorer/Packages/packages-lock.json
  Explorer/ProjectSettings/GraphicsSettings.asset
Labels: no review, do not merge

#4388 fix: emotes asset promise cancellation token disposed exception
  Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/FinalizeEmoteLoadingSystem.cs
Labels: bug

#4379 fix: support multiple unreleased builder emote collections preview
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadOwnedEmotesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/ResolveBuilderEmotePromisesSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/ResolveBuilderEmotePromisesSystem.cs.meta
  Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/ResolveWearablePromisesSystem.cs
  Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
Labels: bug, enhancement, clean-build

#4421 fix: scene emote props sometimes not disposing
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs
  Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/EmotePlayer.cs
  Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs
Labels: bug, force-build

#4400 Shape: community card - events
  Explorer/Assets/DCL/Communities/Communities.asmdef
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/CommunityEventsContextMenuConfiguration.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/CommunityEventsContextMenuConfiguration.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/CommunityEventsContextMenuSettings.asset
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/CommunityEventsContextMenuSettings.asset.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListItemView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListItemView.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/PlaceAndEventDTO.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/PlaceAndEventDTO.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCard.prefab
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardEvents.prefab
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/EventItem.prefab
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/EventItem.prefab.meta
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/CommunityEventsResponse.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/CommunityEventsResponse.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetCommunityResponse.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs
  Explorer/Assets/DCL/EventsApi/EventDTO.cs
  Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
  Explorer/Assets/DCL/UI/ButtonWithSelectableStateView.cs
Labels: shape-up

#4436 Community conversations Member list
  Explorer/Assets/DCL/Chat/Assets/ChatCommunityMemberListTittlebar.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatCommunityMemberListTittlebar.prefab.meta
  Explorer/Assets/DCL/Chat/Assets/ChatMemberListTittlebar.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab
  Explorer/Assets/DCL/Chat/Assets/ChatTitlebarDefault.prefab
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerMemberListHelper.cs
  Explorer/Assets/DCL/Chat/ChatInputBoxElement.cs
  Explorer/Assets/DCL/Chat/ChatMemberListView.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatUserData.cs
  Explorer/Assets/DCL/Chat/ChatUserData.cs.meta
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs
Labels: feature, ui, shape-up

#4463 Conversations that receive a message appear at the top of the chat toolbar
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/History/ChatHistory.cs
  Explorer/Assets/DCL/Chat/History/IChatHistory.cs
  Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/IgnoreWithSymbolsChatMessageBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs
  Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs
  Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs
  Explorer/Assets/DCL/PluginSystem/Global/WorldInfoPlugin.cs
Labels: feature, ui, shape-up

#4467 Added default thumbnails to the chat
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/CommunityChatConversationsToolbarViewItem.cs
  Explorer/Assets/DCL/UI/Communities/CommunityThumbnailView.prefab
  Explorer/Assets/DCL/UI/Communities/CommunityTitleView.cs
Labels: feature, ui, shape-up

#4478 fix: game night loading screen text
  Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Labels: clean-build

#4430 fix: set a default value for the Scene Loading Limit
  Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneLoadingLimit/SceneLoadingLimit.cs
Labels: clean-build

#4536 Communities shape: Chat bubbles
  Explorer/Assets/DCL/Chat/ChatBubbleComponent.cs
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatControllerChatBubblesHelper.cs
  Explorer/Assets/DCL/NameTags/Assets/NametagObject.prefab
  Explorer/Assets/DCL/NameTags/NametagView.cs
  Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Labels: ui, shape-up

#4526 Shape: misc community card improvements
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardContextMenuConfiguration.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/ConfirmationDialogView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/CommunityMemberListContextMenuConfiguration.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/CommunityMemberListContextMenuSettings.asset
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/FriendshipHelpers.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/FriendshipHelpers.cs.meta
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardMembers.prefab
  Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/ConfirmationPopup.prefab
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/Configs/ButtonContextMenuControlSettings.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/GenericContextMenuButtonWithTextView.cs
Labels: shape-up

#4484 Sprite caching system for UI images
  Explorer/Assets/DCL/Chat/ChatController.cs
  Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs
  Explorer/Assets/DCL/Chat/ChatMemberListView.cs
  Explorer/Assets/DCL/Chat/ChatMemberListViewItem.cs
  Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs
  Explorer/Assets/DCL/Chat/ChatTitleBarView.cs
  Explorer/Assets/DCL/Chat/ChatView.cs
  Explorer/Assets/DCL/Chat/CommunityChatConversationsToolbarViewItem.cs
  Explorer/Assets/DCL/Chat/PrivateChatConversationsToolbarViewItem.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardParameter.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/ConfirmationDialogView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListItemView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MemberListItemView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlaceCardView.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs
  Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs
  Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/CreateOrUpdateCommunityResponse.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionParameter.cs
  Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
  Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
  Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCredits.asmdef
  Explorer/Assets/DCL/Navmap/Navmap.asmdef
  Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs
  Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
  Explorer/Assets/DCL/Profiles/Thumbnails/IThumbnailCache.cs
  Explorer/Assets/DCL/Profiles/Thumbnails/ThumbnailCache.cs
  Explorer/Assets/DCL/RewardPanel/RewardPanel.asmdef
  Explorer/Assets/DCL/TeleportPrompt/TeleportPrompt.asmdef
  Explorer/Assets/DCL/UI/Communities/CommunityThumbnailView.cs
  Explorer/Assets/DCL/UI/Communities/CommunityTitleView.cs
  Explorer/Assets/DCL/UI/GenericContextMenu/Controls/GenericContextMenuUserProfileView.cs
  Explorer/Assets/DCL/UI/ISpriteCache.cs
  Explorer/Assets/DCL/UI/ISpriteCache.cs.meta
  Explorer/Assets/DCL/UI/ImageController.cs
  Explorer/Assets/DCL/UI/Profiles/Helpers/DCL.UI.Profiles.Helpers.asmdef
  Explorer/Assets/DCL/UI/Profiles/Helpers/ProfileRepositoryWrapper.cs
  Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
  Explorer/Assets/DCL/UI/SpriteCache.cs
  Explorer/Assets/DCL/UI/SpriteCache.cs.meta
  Explorer/Assets/DCL/UI/Utilities/DCL.UI.Utilities.asmdef
Labels: refactor, performance, shape-up, clean-build

#4550 chore: Clean SettingsDataStore
  Explorer/Assets/DCL/Prefs/DCLPlayerPrefs.cs
  Explorer/Assets/DCL/Prefs/FileDCLPlayerPrefs.cs
  Explorer/Assets/DCL/Prefs/IDCLPrefs.cs
  Explorer/Assets/DCL/Prefs/InMemoryDCLPlayerPrefs.cs
  Explorer/Assets/DCL/Prefs/UnityDCLPlayerPrefs.cs
  Explorer/Assets/DCL/Settings/ISettingsDataStore.cs
  Explorer/Assets/DCL/Settings/ISettingsDataStore.cs.meta
  Explorer/Assets/DCL/Settings/ModuleControllers/AvatarSoundsVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/ChatBubblesVisibilityController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/ChatSoundsSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/EnvironmentDistanceSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/FpsLimitSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/GraphicsQualitySettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/GraphicsVSyncController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/HideBlockedUsersChatMessagesController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MasterVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MemoryLimitSettingController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MouseHorizontalSensitivitySettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MouseVerticalSensitivitySettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/MusicVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/ResolutionSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/SceneDistanceSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/SettingsFeatureController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/UISoundsVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/WindowModeSettingsController.cs
  Explorer/Assets/DCL/Settings/ModuleControllers/WorldSoundsVolumeSettingsController.cs
  Explorer/Assets/DCL/Settings/SettingsDataStore.cs
  Explorer/Assets/DCL/Settings/SettingsDataStore.cs.meta
  Explorer/Assets/DCL/Settings/UpscalingController.cs
Labels: clean-build
